### ISSUE TITLE
Facebook and Instagram Prices

### ISSUE THREAD

**Issue by famuser** [woocommerce/facebook-for-woocommerce#2008] opened 2021-06-09 03:00 UTC
## 🔎 Isolate the bug
X

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
 The prices sometimes are shown in the facebook and instagram shopping without tax. It varies from products time to time and would go back to with tax randomly.

## 🚶‍♀️ Steps to reproduce
 updated website - issues still there.

1. The first step
1. The next step… 

## ✔️ Expected behavior
 prices should display correctly with tax

## 🗃 Logs
 

<details>
	 www.freckledfrog.com.au

Version 2.5.1 for Facebook for woocommerce, Version 5.3.0 for woocommerce, version 5.7.2 wordpress, version 7.4 php
</details>

**Comment by haszari** [comment] 2021-06-09 23:42
Thanks for reporting this @famuser ! Can you give us more details of how we can reproduce the bug?

**Comment by famuser** [comment] 2021-06-11 02:08
> Thanks for reporting this @famuser ! Can you give us more details of how we can reproduce the bug?

We have had your facebook plugin for many years now and our shop feature has been on our account for a while too. However we have not changed anything differently that would impact any changes to the prices excluding tax, but we have recently started experiencing this issue where the price would suddenly change to ex tax and it would be for some products but not all. Just over a week ago 80% of the prices changed to ex tax I had to go into woo commerce and refresh all the products that changed and it went back to normal price. But now there are about 15% of our products that are once again slowly showing up as ex tax on the instagram/facebook shop.

**Comment by famuser** [comment] 2021-06-16 00:45
> Thanks for reporting this @famuser ! Can you give us more details of how we can reproduce the bug?

Any update on this one, please?

**Comment by haszari** [comment] 2021-06-16 01:15
> > Thanks for reporting this @famuser ! Can you give us more details of how we can reproduce the bug?

> Any update on this one, please? @haszari

Thanks for providing more info about how this is impacting your store. To find out what's happening we need steps to reproduce the problem reliably on a basic store setup running just WooCommerce and Facebook for WooCommerce.

**Comment by famuser** [comment] 2021-06-16 01:52
@haszari 
![1623807647175](https://user-images.githubusercontent.com/85598004/122145793-7f353680-ce88-11eb-9b02-d7a8b9a4387d.JPEG)

its so random it changes every day the ones are ive circled are prices ex tax
the others are showing correct price but could change back 2 hrs later and another product will be ex tax
we dont do anything change anything. Do you want me to record my screen so you can see what we usually do to get this error?

**Comment by haszari** [comment] 2021-06-16 02:38
@famuser Thanks for investigating! A screen recording might be useful - especially if this bug is triggered by something you're doing (e.g. editing products). 

A couple of ideas:

- Do you have any staging, test or development sites running? If another similar site is connected to the same business in Facebook, it might be syncing to the production catalog.
- Do you have a feed (data source) configured in Facebook, and pulling (uploading) the feed file from your site? Products can be synced in a variety of ways, using the [Batch API](https://developers.facebook.com/docs/commerce-platform/catalog/batch-api/) and/or a [feed file](https://www.facebook.com/business/help/1898524300466211). Maybe you have an old feed file which is overwriting the correct product info from Batch API?

**Comment by famuser** [comment] 2021-06-16 03:33
I appreciate your help! We don't know what information we can give you to replicate this. Can you guide us?

FYI it is connected to our facebook shop and the plugin we use to connect the facebook shop and woocommerece is the plugin facebook for woocommerce

**Comment by famuser** [comment] 2021-06-22 02:00
@haszari  our products are synced using API - facebook for woocommerce we do not uploading using feed file
we do not have staging site connected to facebook for woocommerce and the products are synced using only Batch API facebook for woocommerce

Your thoughts on this, please?

**Comment by famuser** [comment] 2021-06-23 03:17
Hi @haszari following up on this one, please.

**Comment by haszari** [comment] 2021-06-23 20:26
Hi @famuser - we can't use this repository for tech support. I'd suggest you start a thread about this issue in the [support forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/). 

If you know steps to reliably reproduce the problem, please open a new issue with exact details for reproducing it on a new Woo store running the latest WooCommerce and Facebook for WooCommerce plugin. 

I'm going to close this issue now as we can't reproduce the problem.

**Closed by haszari** 2021-06-23 20:26 UTC
Labels: feature: product sync, needs feedback
