### ISSUE TITLE
Can't reset meta data - JavaScript error

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/facebook-for-woocommerce#1979] opened 2021-05-27 00:12 UTC
## 🔎 Isolate the bug

- [x ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

As reported in this support thread: https://wordpress.org/support/topic/reset-meta-data-broken-since-last-update

When clicking the "Reset Facebook metadata" the metadata is not reset and in fact, nothing happens except for a JavaScript error i.e. `Uncaught ReferenceError: fb_reset_product is not defined`

## 🚶‍♀️ Steps to reproduce
1. Facebook for WooCommerce 2.5.0+
2. Go to `Products` and edit a product. 
3. Scroll down to `Facebook` metabox and click `Reset Facebook metadata`.
3. See JavaScript error: `Uncaught ReferenceError: fb_reset_product is not defined`

<img width="540" alt="Screen Shot 2021-05-27 at 1 17 13 PM" src="https://user-images.githubusercontent.com/4167300/119750811-24926580-beee-11eb-974f-e5058a81b6ca.png">
<img width="556" alt="Screen Shot 2021-05-27 at 1 19 26 PM" src="https://user-images.githubusercontent.com/4167300/119750826-2b20dd00-beee-11eb-8172-e8af7a5c1b75.png">

## ✔️ Expected behavior
That the metadata is reset as advertised by the anchor text.

Pre 2.5 this would show a modal confirm prompt, and then the metabox would show `This product is not yet synced to Facebook.` state.

<img width="484" alt="Screen Shot 2021-05-27 at 1 20 59 PM" src="https://user-images.githubusercontent.com/4167300/119751253-ea759380-beee-11eb-8f27-6b28a84cbf86.png">
<img width="400" alt="Screen Shot 2021-05-27 at 1 24 45 PM" src="https://user-images.githubusercontent.com/4167300/119751255-ec3f5700-beee-11eb-885a-3408935b205a.png">

## 🗃 Logs

<details>
### WordPress Environment ###
WordPress address (URL): https://domain.deSite address (URL): https://domain.deWC Version: 5.3.0REST API Version: ✔ 5.3.0WC Blocks Version: ✔ 4.9.1Action Scheduler Version: ✔ 3.1.6WC Admin Version: ✔ 2.2.6Log Directory Writable: ✔WP Version: 5.7.2WP Multisite: –WP Memory Limit: 512 MBWP Debug Mode: –WP Cron: ✔Language: de_DEExternal object cache: –
### Server Environment ###
Server Info: nginx/1.17.5PHP Version: 7.4.10PHP Post Max Size: 2 GBPHP Time Limit: 120PHP Max Input Vars: 10000cURL Version: 7.47.0OpenSSL/1.0.2g
SUHOSIN Installed: –MySQL Version: 5.5.5-10.2.33-MariaDB-10.2.33+maria~xenial-logMax Upload Size: 2 GBDefault Timezone is UTC: ✔fsockopen/cURL: ✔SoapClient: ✔DOMDocument: ✔GZip: ✔Multibyte String: ✔Remote Post: ✔Remote Get: ✔
### Database ###
WC Database Version: 5.3.0WC Database Prefix: wp_kskskdk_Datenbank-Gesamtgröße: 864.77MBDatenbank-Datengröße: 481.74MBDatenbank-Indexgröße: 383.03MBwp_anrbeqgweb_woocommerce_sessions: Daten: 9.02MB + Index: 0.05MB + Engine InnoDBwp_anrbeqgweb_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDBwp_anrbeqgweb_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDBwp_anrbeqgweb_woocommerce_order_items: Daten: 4.52MB + Index: 1.52MB + Engine InnoDBwp_anrbeqgweb_woocommerce_order_itemmeta: Daten: 34.56MB + Index: 30.86MB + Engine InnoDBwp_anrbeqgweb_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDBwp_anrbeqgweb_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDBwp_anrbeqgweb_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDBwp_anrbeqgweb_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDBwp_anrbeqgweb_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_actionscheduler_actions: Daten: 9.02MB + Index: 7.42MB + Engine InnoDBwp_anrbeqgweb_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_actionscheduler_logs: Daten: 5.02MB + Index: 5.03MB + Engine InnoDBwp_anrbeqgweb_borlabs_cookie_consent_log: Daten: 23.05MB + Index: 9.48MB + Engine InnoDBwp_anrbeqgweb_borlabs_cookie_content_blocker: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_borlabs_cookie_cookies: Daten: 0.02MB + Index: 0.03MB + Engine InnoDBwp_anrbeqgweb_borlabs_cookie_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_borlabs_cookie_script_blocker: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_commentmeta: Daten: 0.30MB + Index: 0.31MB + Engine InnoDBwp_anrbeqgweb_comments: Daten: 18.55MB + Index: 15.05MB + Engine InnoDBwp_anrbeqgweb_ea_appointments: Daten: 0.02MB + Index: 0.05MB + Engine InnoDBwp_anrbeqgweb_ea_connections: Daten: 0.02MB + Index: 0.05MB + Engine InnoDBwp_anrbeqgweb_ea_error_logs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_ea_fields: Daten: 0.06MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_ea_locations: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_ea_meta_fields: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_ea_options: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_ea_services: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_ea_staff: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_elfsight_instagram_feed_widgets: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_jtl_connector_category_level: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_jtl_connector_link_category: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_jtl_connector_link_crossselling: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_jtl_connector_link_crossselling_group: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_jtl_connector_link_currency: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_jtl_connector_link_customer: Daten: 0.02MB + Index: 0.03MB + Engine InnoDBwp_anrbeqgweb_jtl_connector_link_customer_group: Daten: 0.02MB + Index: 0.03MB + Engine InnoDBwp_anrbeqgweb_jtl_connector_link_image: Daten: 0.02MB + Index: 0.03MB + Engine InnoDBwp_anrbeqgweb_jtl_connector_link_language: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_jtl_connector_link_manufacturer: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_jtl_connector_link_measurement_unit: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_jtl_connector_link_order: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_jtl_connector_link_payment: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_jtl_connector_link_product: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_jtl_connector_link_shipping_class: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_jtl_connector_link_shipping_method: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_jtl_connector_link_specific: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_jtl_connector_link_specific_value: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_jtl_connector_product_checksum: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_mailchimp_carts: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_mailchimp_jobs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_options: Daten: 33.31MB + Index: 5.47MB + Engine InnoDBwp_anrbeqgweb_postmeta: Daten: 129.67MB + Index: 95.00MB + Engine InnoDBwp_anrbeqgweb_posts: Daten: 20.41MB + Index: 8.69MB + Engine InnoDBwp_anrbeqgweb_pum_subscribers: Daten: 0.02MB + Index: 0.06MB + Engine InnoDBwp_anrbeqgweb_sbi_instagram_feeds_posts: Daten: 0.02MB + Index: 0.03MB + Engine InnoDBwp_anrbeqgweb_sbi_instagram_feed_locator: Daten: 0.02MB + Index: 0.03MB + Engine InnoDBwp_anrbeqgweb_sbi_instagram_posts: Daten: 1.52MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_sib_model_forms: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_sib_model_users: Daten: 1.52MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_ssa_appointments: Daten: 0.02MB + Index: 0.08MB + Engine InnoDBwp_anrbeqgweb_ssa_appointment_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDBwp_anrbeqgweb_ssa_appointment_types: Daten: 0.02MB + Index: 0.06MB + Engine InnoDBwp_anrbeqgweb_ssa_async_actions: Daten: 0.02MB + Index: 0.11MB + Engine InnoDBwp_anrbeqgweb_ssa_availability: Daten: 0.02MB + Index: 0.14MB + Engine InnoDBwp_anrbeqgweb_ssa_availability_external: Daten: 0.02MB + Index: 0.14MB + Engine InnoDBwp_anrbeqgweb_stock_log: Daten: 1.52MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_storeabill_documentmeta: Daten: 25.56MB + Index: 20.03MB + Engine InnoDBwp_anrbeqgweb_storeabill_documents: Daten: 3.52MB + Index: 1.55MB + Engine InnoDBwp_anrbeqgweb_storeabill_document_itemmeta: Daten: 34.56MB + Index: 29.00MB + Engine InnoDBwp_anrbeqgweb_storeabill_document_items: Daten: 5.52MB + Index: 4.52MB + Engine InnoDBwp_anrbeqgweb_storeabill_document_noticemeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDBwp_anrbeqgweb_storeabill_document_notices: Daten: 2.52MB + Index: 1.52MB + Engine InnoDBwp_anrbeqgweb_storeabill_journals: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_termmeta: Daten: 2.52MB + Index: 5.03MB + Engine InnoDBwp_anrbeqgweb_terms: Daten: 0.11MB + Index: 0.09MB + Engine InnoDBwp_anrbeqgweb_term_relationships: Daten: 2.41MB + Index: 1.30MB + Engine InnoDBwp_anrbeqgweb_term_taxonomy: Daten: 0.13MB + Index: 0.16MB + Engine InnoDBwp_anrbeqgweb_usermeta: Daten: 7.25MB + Index: 5.88MB + Engine InnoDBwp_anrbeqgweb_users: Daten: 0.23MB + Index: 0.23MB + Engine InnoDBwp_anrbeqgweb_wcpdf_invoice_number: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_wc_customer_lookup: Daten: 0.52MB + Index: 0.41MB + Engine InnoDBwp_anrbeqgweb_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDBwp_anrbeqgweb_wc_gpf_render_cache: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_wc_order_coupon_lookup: Daten: 0.09MB + Index: 0.13MB + Engine InnoDBwp_anrbeqgweb_wc_order_product_lookup: Daten: 3.52MB + Index: 3.95MB + Engine InnoDBwp_anrbeqgweb_wc_order_stats: Daten: 1.52MB + Index: 1.11MB + Engine InnoDBwp_anrbeqgweb_wc_order_tax_lookup: Daten: 1.52MB + Index: 0.78MB + Engine InnoDBwp_anrbeqgweb_wc_product_meta_lookup: Daten: 1.52MB + Index: 1.33MB + Engine InnoDBwp_anrbeqgweb_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_wfblockediplog: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_wfblocks7: Daten: 0.02MB + Index: 0.05MB + Engine InnoDBwp_anrbeqgweb_wfconfig: Daten: 0.45MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_wfcrawlers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_wffilechanges: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_wffilemods: Daten: 2.52MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_wfhits: Daten: 0.02MB + Index: 0.05MB + Engine InnoDBwp_anrbeqgweb_wfhoover: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_wfissues: Daten: 0.02MB + Index: 0.06MB + Engine InnoDBwp_anrbeqgweb_wfknownfilelist: Daten: 1.52MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_wflivetraffichuman: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_wflocs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_wflogins: Daten: 0.02MB + Index: 0.03MB + Engine InnoDBwp_anrbeqgweb_wfls_2fa_secrets: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_wfls_settings: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_wfnotifications: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_wfpendingissues: Daten: 0.02MB + Index: 0.06MB + Engine InnoDBwp_anrbeqgweb_wfreversecache: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_wfsnipcache: Daten: 0.02MB + Index: 0.05MB + Engine InnoDBwp_anrbeqgweb_wfstatus: Daten: 0.08MB + Index: 0.03MB + Engine InnoDBwp_anrbeqgweb_wftrafficrates: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_woocommerce_gpf_google_taxonomy: Daten: 1.52MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDBwp_anrbeqgweb_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDBwp_anrbeqgweb_woocommerce_gzd_dhl_labelmeta: Daten: 2.52MB + Index: 3.00MB + Engine InnoDBwp_anrbeqgweb_woocommerce_gzd_dhl_labels: Daten: 1.52MB + Index: 0.20MB + Engine InnoDBwp_anrbeqgweb_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDBwp_anrbeqgweb_woocommerce_gzd_shipmentmeta: Daten: 6.52MB + Index: 5.00MB + Engine InnoDBwp_anrbeqgweb_woocommerce_gzd_shipments: Daten: 2.52MB + Index: 0.56MB + Engine InnoDBwp_anrbeqgweb_woocommerce_gzd_shipment_itemmeta: Daten: 4.50MB + Index: 5.03MB + Engine InnoDBwp_anrbeqgweb_woocommerce_gzd_shipment_items: Daten: 2.50MB + Index: 1.47MB + Engine InnoDBwp_anrbeqgweb_woocommerce_gzd_shipment_labelmeta: Daten: 0.42MB + Index: 0.50MB + Engine InnoDBwp_anrbeqgweb_woocommerce_gzd_shipment_labels: Daten: 0.09MB + Index: 0.03MB + Engine InnoDBwp_anrbeqgweb_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDBwp_anrbeqgweb_wpjf3_mr_access_keys: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_wpjf3_mr_unrestricted_ips: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_wpmailsmtp_tasks_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDBwp_anrbeqgweb_wsal_metadata: Daten: 47.08MB + Index: 90.34MB + Engine InnoDBwp_anrbeqgweb_wsal_occurrences: Daten: 3.02MB + Index: 5.03MB + Engine InnoDBwp_anrbeqgweb_yith_wcwl: Daten: 0.31MB + Index: 0.09MB + Engine InnoDBwp_anrbeqgweb_yith_wcwl_lists: Daten: 0.09MB + Index: 0.08MB + Engine InnoDBwp_anrbeqgweb_yoast_indexable: Daten: 14.52MB + Index: 12.27MB + Engine InnoDBwp_anrbeqgweb_yoast_indexable_hierarchy: Daten: 1.31MB + Index: 1.03MB + Engine InnoDBwp_anrbeqgweb_yoast_migrations: Daten: 0.02MB + Index: 0.02MB + Engine InnoDBwp_anrbeqgweb_yoast_primary_term: Daten: 0.16MB + Index: 0.16MB + Engine InnoDBwp_anrbeqgweb_yoast_seo_links: Daten: 0.08MB + Index: 0.03MB + Engine InnoDBwp_anrbeqgweb_yoast_seo_meta: Daten: 1.50MB + Index: 0.00MB + Engine InnoDB
### Post Type Counts ###
attachment: 6679blossom-portfolio: 1custom_css: 3customize_changeset: 2cwginstocknotifier: 4473document_template: 12feedback: 1gift_card: 108invoice: 1638nav_menu_item: 114oembed_cache: 9page: 31popup: 2popup_theme: 8post: 11product: 1290product_variation: 5448revision: 1791shop_coupon: 124shop_order: 10481shop_order_refund: 3933subscribe-form: 1yith-wcbm-badge: 3
### Security ###
Secure connection (HTTPS): ✔Hide errors from visitors: ✔
### Active Plugins (37) ###
Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro: von codewoogeek – 2.1Borlabs Cookie - Cookie Opt-in: von Benjamin A. BornscheinBorlabs – 2.2.25
EAN for WooCommerce: von Algoritmika Ltd – 2.1.1Easy Appointments: von Nikola Loncar – 3.5.2Envato Market: von Envato – 2.0.6Facebook for WooCommerce: von Facebook – 2.5.0HookMeUp – Additional Content for WooCommerce: von GetBowtied – 1.3.3Smash Balloon Instagram Feed: von Smash Balloon – 2.9.1Jetpack von WordPress.com: von Automattic – 9.7Klarna Checkout for WooCommerce: von Krokedil – 2.5.4Klarna Order Management for WooCommerce: von klarnakrokedil – 1.6.7
Newsletter, SMTP, Email marketing and Subscribe forms by Sendinblue: von Sendinblue – 3.1.13Popup Maker: von Popup Maker – 1.16.1Regenerate Thumbnails: von Alex Mills (Viper007Bond) – 3.1.5Shopkeeper Deprecated Features: von GetBowtied – 1.1.6Shopkeeper Extender: von GetBowtied – 1.6.9Shopkeeper Portfolio Addon: von GetBowtied – 1.3.5Vendidero Helper: von Vendidero – 1.3.0WooCommerce JTL-Connector: von JTL-Software GmbH – 1.23.2Advanced Order Export For WooCommerce: von AlgolPlus – 3.1.8Woo PayJoe Beleg Schnittstelle: von WESLINK - Let's Web | Site Shop App – 1.6.1PayPal PLUS für WooCommerce: von Inpsyde GmbH – 2.2.1Variation Swatches for WooCommerce: von Emran Ahmed – 1.1.17WooSwatches - Woocommerce Color or Image Variation Swatches: von woomatrix – 2.8.7WooCommerce Colors: von WooThemes – 1.0.7WooCommerce PayPal Checkout Gateway: von WooCommerce – 2.1.1Germanized für WooCommerce Pro: von vendidero – 3.2.2Germanized für WooCommerce: von vendidero – 3.4.8WooCommerce Google Product Feed: von Ademti Software Ltd. – 9.6.4 (Update auf Version 9.6.7 ist verfügbar)WooCommerce Stock Manager: von StoreApps – 2.5.7WooCommerce: von Automattic – 5.3.0Yoast SEO: von Team Yoast – 16.3WP Mail SMTP: von WPForms – 2.8.0WP Activity Log: von WP White Security – 4.3.0YITH WooCommerce Badge Management: von YITH – 1.4.12YITH WooCommerce Gift Cards: von YITH – 2.0.14YITH WooCommerce Wishlist: von YITH – 3.0.22
### Inactive Plugins (2) ###
WooCommerce Admin: von WooCommerce – 2.3.0WP Activity Log for WooCommerce: von WP White Security – 1.2.2
### Must Use Plugins (1) ###
disable_admin_mail.php: von  –
### Settings ###
API Enabled: –Force SSL: ✔Currency: EUR (€)Currency Position: right_spaceThousand Separator: .Decimal Separator: ,Number of Decimals: 2Taxonomies: Product Types: external (external)gift-card (gift-card)grouped (grouped)simple (simple)variable (variable)
Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)exclude-from-search (exclude-from-search)featured (featured)outofstock (outofstock)rated-1 (rated-1)rated-2 (rated-2)rated-3 (rated-3)rated-4 (rated-4)rated-5 (rated-5)
Connected to WooCommerce.com: ✔
### WC Pages ###
Shop-Basis: #27 - /shop/Warenkorb: #28 - /warenkorb/Kasse: #29 - /kasse/Mein Konto: #30 - /mein-konto/Allgemeine Geschäftsbedingungen: #108 - /agb/
### Theme ###
Name: Shopkeeper ChildVersion: 1.0Author URL: http:%20//www.getbowtied.com/Child Theme: ✔Parent Theme Name: ShopkeeperParent Theme Version: 2.9.44Parent Theme Author URL: https://www.getbowtied.com/WooCommerce Support: ✔
### Templates ###
Overrides: shopkeeper/woocommerce/archive-product.phpshopkeeper/woocommerce/checkout/form-coupon.phpshopkeeper/woocommerce/checkout/form-login.phpshopkeeper/woocommerce/content-product.phpshopkeeper/woocommerce/content-single-product.phpshopkeeper/woocommerce/global/quantity-input.phpshopkeeper/woocommerce/global/sidebar.phpshopkeeper/woocommerce/global/wrapper-end.phpshopkeeper/woocommerce/global/wrapper-start.phpshopkeeper/woocommerce/myaccount/form-login.phpshopkeeper/woocommerce/single-product/add-to-cart/simple.phpshopkeeper/woocommerce/single-product/product-image.phpshopkeeper/woocommerce/single-product/product-thumbnails.phpshopkeeper/woocommerce/single-product/tabs/tabs.phpshopkeeper/woocommerce/single-product.php

### WooCommerce Google Product Feed options ###
Google merchant centre product feed: EnabledGoogle merchant centre product review feed: -Bing merchant centre feed: -Google merchant centre local product inventory feed: -Google merchant centre local products feed (legacy): -Google merchant centre product inventory feed (legacy): -Include variations in feed: EnabledSend "item group ID": -Expanded schema markup: -Debug key: 9315a084-ad1c-46e4-b913-6a7ecd43e18b
### WooCommerce Google Product Feed fields ###
Title: Pre-populates from product product_title.Availability: Defaults to "in stock".Brand: Manufacturer Part Number (MPN): Product Type: Google Product Category: Size system: 
### Action Scheduler ###
Complete: 16.691Oldest: 2021-04-25 16:00:46 +0200Newest: 2021-05-26 15:52:03 +0200
Failed: 967Oldest: 2021-02-21 20:38:42 +0100Newest: 2021-03-09 11:55:39 +0100
Pending: 3Oldest: 2021-05-27 03:49:08 +0200Newest: 2021-05-27 12:05:57 +0200

### Status report information ###
Generated at: 2021-05-26 15:56:46 +02:00

</details>

**Comment by haszari** [comment] 2021-05-27 01:23
Tested and confirmed this issue on `master` branch, and confirmed that this is not broken in `2.4.1` tag. So it looks like we introduced this as part of the JS tidy up - good catch! Adding critical label since this is an introduced issue.

Also updated the testing instructions in description.

**Comment by haszari** [comment] 2021-05-27 01:27
I'll look at getting a fix for this. Hopefully we can track down the old JS code - I'm not familiar with this feature. 

@WillBrubaker (or anyone affected) - can you add some info about how this `Reset Facebook metadata` fits into your product sync workflow? E.g. when you need to reset metadata and why, what's the wider goal there. While I'm here I want to make sure I understand how this fits in to the bigger picture :)

**Comment by WillBrubaker** [comment] 2021-05-27 01:32
The forum thread is what brought me here. Perhaps the OP can provide some insight.

We do have 4014280-zen and if the product sync workflow hadn't failed to begin with, we probably wouldn't be where we are, but we need this same functionality there to try and reset that product so we can try again to sync it up.

**Comment by haszari** [comment] 2021-05-27 01:34
Thanks - so this is being used in a "reset / clear / nuke it so I can start again" flow. 

Note - we still have the function so it maybe just an enqueuing assets issue. Stay tuned!

https://github.com/woocommerce/facebook-for-woocommerce/blob/c6143773a1613ec41a3a138ee3af6a3cda138e54/assets/js/admin/metabox.js#L38-L58

**Comment by solstudioim** [comment] 2021-05-27 05:05
I could replicate this as well on 2.5.0

**Comment by AashikP** [comment] 2021-05-27 08:49
Another report in 4022847-zen

**Comment by despecial** [comment] 2021-05-27 08:50
Client reports that version 2.5.0 also has a problem with deleting products via metabox.
So I guess it's the build process for this metabox.js which is not working as planned.

**Closed** 2021-05-27 22:50 UTC
Labels: priority: critical, type: bug

**Comment by haszari** [comment] 2021-05-28 03:12
The fix for this has now been released - update stores to 2.5.1+ and the metabox should be working correctly again.
