### ISSUE TITLE
Unable to sync product catalog

### ISSUE THREAD

**Issue by oceanlivingfoods** [woocommerce/facebook-for-woocommerce#2676] opened 2023-12-28 19:57 UTC
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
1. WooCommerce for Facebook plugin can **create** a product, and the new product appears in the Commerce Manager catalog, but any updates to the product that was just created by the plugin returns the following error:

```
12-10-2023 @ 04:08:08 - Request
method: POST
uri: https://graph.facebook.com/v17.0/7100195296754519
user-agent: Facebook-for-WooCommerce/3.1.5 (WooCommerce/8.3.1; WordPress/6.4.2)
body: {"name":"Test Book","description":"Test Book","image_url":"https:\/\/rawvegan.love\/wp-content\/uploads\/2023\/08\/French-Cuisine-Cover.png","additional_image_urls":"","url":"https:\/\/rawvegan.love\/shop\/test-book\/","category":"Uncategorized","product_type":"Uncategorized","brand":"RawVegan.Love","retailer_id":"wc_post_id_2595","price":199,"currency":"USD","availability":"in stock","visibility":"hidden","sale_price_start_date":"1970-01-29T00:00+00:00","sale_price_end_date":"2038-01-17T23:59+00:00","sale_price":0}
duration: 0.57398s

12-10-2023 @ 04:08:08 - Response
code: 400
message: Bad Request
body: {"error":{"message":"Unsupported post request. Object with ID '7100195296754519' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https:\/\/developers.facebook.com\/docs\/graph-api","type":"GraphMethodException","code":100,"error_subcode":33,"fbtrace_id":"AlQDP5C-jlIN0IuuoW900EZ"}}

12-10-2023 @ 04:08:08 - Updated product  7100195296754519 on Facebook has failed.
```

When I try to look up the handle for the Graph API on Facebook, Facebook shows an error page (the handle lookup screen appears to be broken on Facebook).

![Screenshot 2023-12-09 201848](https://github.com/woocommerce/facebook-for-woocommerce/assets/144002227/de275c70-a7e2-4b16-ad00-0924fe5282a9)

2. Any product where I "Reset the Facebook metadata" in the "Facebook Product Sync" section of the product page permanently prevents that product from being synced again, either by updating the product or using the manual "Sync Products" button in the Product Sync tab of the plugin. And yes, the "Sync and hide in catalog" option is enabled for all of those products.

3. Products that were created by the plugin are not deleted from the Catalog using the "Delete product(s) from Facebook" link on the Product page. It only resets the "Facebook Product Sync" section to say _This product is not yet synced to Facebook_, and I cannot get the product to re-sync. Here is the error:

```
12-10-2023 @ 05:07:45 - Request
method: DELETE
uri: https://graph.facebook.com/v17.0/7100195296754519
user-agent: Facebook-for-WooCommerce/3.1.5 (WooCommerce/8.3.1; WordPress/6.4.2)
body:
duration: 0.17197s

12-10-2023 @ 05:07:45 - Response
code: 400
message: Bad Request
body: {"error":{"message":"Unsupported delete request. Object with ID '7100195296754519' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https:\/\/developers.facebook.com\/docs\/graph-api","type":"GraphMethodException","code":100,"error_subcode":33,"fbtrace_id":"AmhaRoiVw5VWIYIag0_74eJ"}}

12-10-2023 @ 05:07:45 - {"response_data":{"error":{"message":"Unsupported delete request. Object with ID '7100195296754519' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https:\/\/developers.facebook.com\/docs\/graph-api","type":"GraphMethodException","code":100,"error_subcode":33,"fbtrace_id":"AmhaRoiVw5VWIYIag0_74eJ"}}}
12-10-2023 @ 05:07:45 - Request
method: DELETE
uri: https://graph.facebook.com/v17.0/7100195246754524?deletion_method=delete_items
user-agent: Facebook-for-WooCommerce/3.1.5 (WooCommerce/8.3.1; WordPress/6.4.2)
body:
duration: 0.24293s
```

This is an integration that was working for over a year, and broke maybe in May or April of this year.  Deleting and recreating my catalog again is not an option, as it takes several months for Facebook to re-approve the site, and the Instagram and Facebook side of things are working perfectly, with many tagged products in my posts and Checkout enabled within Instagram. I lost months of sales trying to fix this issue myself when I started the Catalog again from scratch trying to fix the sync issue.

Right now, the plugin can only be used to **create** products on the catalog, but not **update** or **delete** products, even those that were created by the plugin. This was working properly earlier in 2023 without any changes to my products.

One other thing that I noticed is that the WooCommerce for Facebook plugin is listed as a System user for the Pixel, which is working fine, but not for the Catalog (see screenshot). However, it doesn't make sense that the Facebook for WooCommerce app would be allowed to create products but not update or delete them.

![Screenshot 2023-12-09 211503](https://github.com/woocommerce/facebook-for-woocommerce/assets/144002227/442d7f5d-b937-4ac0-9a94-d54bac79e692)
![Screenshot 2023-12-09 211638](https://github.com/woocommerce/facebook-for-woocommerce/assets/144002227/67fdc0e0-b28b-4860-ac12-b1889bbda286)
![Screenshot 2023-12-09 211704](https://github.com/woocommerce/facebook-for-woocommerce/assets/144002227/4b5e2807-1566-456f-ade4-79fa0e872af6)

I understand that you're not able to recreate this issue with a brand new account, but that doesn't help me, because I can't create my entire catalog and website from scratch again. This was working properly before some sort of update happened, and broke most likely because Facebook published a newer version of GraphAPI, which requires more explicit permissions for apps.

I noticed another user reported the same issue at https://github.com/woocommerce/facebook-for-woocommerce/issues/2656, so I believe this issue is **not** isolated to my installation.

What else do you need me to provide in order to fix this problem? My system report has not changed from the one that I pasted earlier in this thread. I am willing to hop on a Zoom call so that you can look at my database and whatever else you need in order to debug the problem.

## 🚶‍♀️ Steps to reproduce

1. Create a product and sync it to Facebook.
2. Observe that the product is created.
3. Edit the product and publish it.
4. Observe that publishing the product produces an error.
5. Reset the Facebook metadata from the product.
6. Edit the product again and publish it.
7. Observe that publishing the product no longer tries to sync to Facebook with no way to re-enable the sync

## ✔️ Expected behavior
1. Existing products should sync properly to Instagram
2. Removing the Facebook metadata should not permanently disable the sync.

## 🗃 Logs

<details>
	see logs above
</details>

**Comment by ecgan** [comment] 2024-01-19 17:47
Adding a note that this issue was previously brought up in https://github.com/woocommerce/facebook-for-woocommerce/issues/2627#issuecomment-1848862323.

**Comment by ecgan** [comment] 2024-01-19 18:40
@oceanlivingfoods , thanks for reaching out. 👋 

> I noticed another user reported the same issue at https://github.com/woocommerce/facebook-for-woocommerce/issues/2656, so I believe this issue is not isolated to my installation.

It seems to me that it is not exactly the same issue. #2656 is specifically about Product Sets, while your issue here is about product catalog.

> What else do you need me to provide in order to fix this problem? My system report has not changed from the one that I pasted earlier in this thread. I am willing to hop on a Zoom call so that you can look at my database and whatever else you need in order to debug the problem.

We looked into the issue and we are not able to reproduce it.

We also did some search around your error messages `"Unsupported post request. Object with ID '7100195296754519' does not exist` and found some results. Perhaps you might find them useful in your troubleshooting with your site.

As noted in https://github.com/woocommerce/facebook-for-woocommerce#support, the best place to get support is the [WordPress.org Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/).

If you have a Woo.com account, you can [search for help or submit a help request on Woo.com](https://woo.com/my-account/contact-support/). Our support team would be able to help you better there.

The plugin also offers logging that can help debug various problems. You can enable debug mode in the main plugin settings panel under the `Enable debug mode` section. By default plugin omits headers in the requests to make the logs more readable. If debugging with headers is necessary you can enable the headers in the logs by setting `wc_facebook_request_headers_in_debug_log` option to true.

I hope this helps. Closing this issue.

**Closed by ecgan** 2024-01-19 18:40 UTC
Labels: needs investigation

**Comment by oceanlivingfoods** [comment] 2024-01-19 18:47
@Gan Eng Chin,

What steps do you do to reproduce the issue? You keep closing this bug
without any resolution, and just passing me off to another forum.

If you review the logs that I supplied, you will see that WooCommerce for
Facebook created a product, but then the error message that you quoted
above is related to the plugin not "finding" the exact same product that it
just created.

Please reopen this issue, and I can provide some time for you to go over
the issue in more detail in a Zoom call.

**Comment by budzanowski** [comment] 2024-01-21 07:48
@oceanlivingfoods

There can be many reasons why you are seeing the error in the logs. The first step is proper troubleshooting of your setup. The links that @ecgan has provided are an excellent starting point.

In case we can't reproduce the problem we are not able to start looking at the code, and code-related activities are what we use GitHub for. Please contact the support channels.

**Comment by oceanlivingfoods** [comment] 2024-01-21 20:12
@budzanowski

I have been debugging this issue for almost 6 months now. I first reported it in the WordPress forums, and then was directed to the GitHub forums, where the issue is now been closed twice due to unable to reproduce.

I have torn down my entire website, torn down my Instagram and Facebook shop, built them both back up from scratch, reinstalled the plugin for both WooCommerce and WooCommerce for Facebook, and then had to go through a several month approval process to get my shop back online with Meta. I lost several months of sales because my shop had to be reapproved from scratch.

I have been on countless calls with Meta, asking for logs of the data source to determine exactly what the issue is, where the plugin can create products but cannot update them. The error message that comes back is very generic, but it is also very odd that the plugin can create a product, but then doesn't have permissions to update it.

I believe this may be a permissions issue with the plug-in on Facebook. It's possible that I may need to update the access token, but at this point, the WooCommerce for Facebook plugin, even though it's installed from scratch, is showing for all new products that it is "not yet synced to Facebook". However, it does send the product up to the commerce manager, but then all updates to that product, or to any other products that was created by the plug-in, come back with the error that I mentioned above.

I believe that there may be some sort of database corruption, with my plugin, where it may not be using the correct access token. But that is just a guess. At this point, it only creates products, and any updates to the products like images, etc have to be done twice, once on the website and once on the commerce manager. Which defeats the whole purpose of the plug-in.

What would help at this point, is if you were able to provide a working installation of the plug-in with WooCommerce all the way through to commerce manager, where you have verified that the commerce manager allows updates to products that were created by the plug-in. If you have tried to reproduce this error, then you have already set this sandbox up. What I would like to do is compare my setup to the one that you used to unsuccessfully reproduce the error, so that I can look to see what the difference is between my setup and the working one.

Can you please provide a sandbox login for your test WordPress site, along with a sandbox login for the Facebook account that it's hooked up to? That seems to be the only way that I will be able to resolve this issue, because over the past 6 months, I spent over 80 hours trying to fix this issue with no success.

**Comment by oceanlivingfoods** [comment] 2024-02-18 17:05
It looks like this was resolved on the Facebook side by allowing legacy updates to the Graph API.

**Comment by ecgan** [comment] 2024-02-20 11:48
> It looks like this was resolved on the Facebook side by allowing legacy updates to the Graph API.

@oceanlivingfoods , thanks so much for letting us know that it was resolved on the Facebook side! Glad that it finally work out for you!
