### ISSUE TITLE
Fatal error uncaght error

### ISSUE THREAD

**Issue by mondemaya** [woocommerce/facebook-for-woocommerce#1730] opened 2020-12-12 05:53 UTC
## 🔎 Isolate the bug

- [x ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

##🚶‍♀️ Steps to reproduce

1. install facebook for woocommerce
1. active it

## ✔️ Expected behavior, see image.. Facebook Marketplace
![facebook marketplace](https://user-images.githubusercontent.com/72323620/101976561-f94fde80-3c0b-11eb-8982-368fc9fa3d14.png)

##
![Imagen1](https://user-images.githubusercontent.com/72323620/101975722-3b752200-3c04-11eb-80fd-671a5b4ba76d.png)
![Imagen1](https://user-images.githubusercontent.com/72323620/101975933-15508180-3c06-11eb-9ffe-fb165fb695a1.png)

 🗃 Logs

**Comment by haszari** [comment] 2021-03-22 02:34
Hi @mondemaya - thanks for reporting this. I can't reproduce this error.

It looks like there might be a conflict with `wc-frontend-manager-ultimate/facebook-marketplace` - are you running any other plugins? Can you reproduce the issue with only WooCommerce and Facebook for WooCommerce active (no other plugins)?

**Comment by haszari** [comment] 2021-04-16 00:46
Closing - we haven't had any other reports of this issue. @mondemaya if you see this issue again, please open a new issue with full details of how to reproduce. Thank you 😀

**Closed by haszari** 2021-04-16 00:46 UTC
