### ISSUE TITLE
2.3.3 update routine breaking WP Admin on stores with a high number of products

### ISSUE THREAD

**Issue by danielbitzer** [woocommerce/facebook-for-woocommerce#1839] opened 2021-03-26 04:33 UTC
Internal incident report: pb0Spc-1tW-p2

## ✍️ Describe the bug

Immediately after updating to [version 2.3.3 ](https://github.com/woocommerce/facebook-for-woocommerce/pull/1797) we have had reports of fatal memory exhaustion errors appearing in WP Admin. In these cases it could only be fixed by deactivating the plugin via WP CLI or FTP.

_I have not done any debugging on the affected sites but based on the evidence I’m very confident of the issue…_ I'm currently generating products on my local site. I currently have 1618 products which is using 134 MB of memory to start the catalog sync.

The 2.3.3 update triggers a full product catalog sync to Facebook in the background immediately when a site updates. Note that this is something that happens normally in the plugin. There is a button to trigger a sync: 

<p>This plugin uses SkyVerge's plugin framework to handle the update routine which is hooked to the  <code>wp_loaded</code> action on admin requests (excluding admin-ajax) (<a href="https://github.com/skyverge/wc-plugin-framework/blob/master/woocommerce/Lifecycle.php#L89">code ref</a>). If the routine throws an error it will continue trying to run the routine on all subsequent admin requests until the plugin is deactivated.</p>

<p>The issue with the product sync code in Facebook for WooCommerce is that it <a href="https://github.com/woocommerce/facebook-for-woocommerce/blob/7af84f0570939eed9d0aad607e27186eae93ce2f/includes/Products/Sync.php#L82-L89">uses an unbounded product query</a> to firstly retrieve every product and then attempts to <a href="https://github.com/woocommerce/facebook-for-woocommerce/blob/7af84f0570939eed9d0aad607e27186eae93ce2f/includes/Products/Sync.php#L176-L187">write a background job for <strong>every product</strong></a> in the same request. Obviously it was just a matter of time until a site has too many products to process in a single request.</p>

@kosiew can also replicate a very similar issue which is reported in #1818

## The solution

We need to remove use of unbounded product database query.

I've observed that there are 2 ways to sync products in this plugin, via **a feed** or **a background job**. Perhaps these do the same thing? If that was the case perhaps one is more scalable and should be used in instances like this. I've asked in slack. If anyone knows please comment.

## Steps to reproduce

- Install [Query Monitor](https://wordpress.org/plugins/query-monitor/)
- Generate a ton of products on your store (use [woocommerce/wc-smooth-generator](https://github.com/woocommerce/wc-smooth-generator)) the exact amount will vary on the server
- Set the `wc_facebook_for_woocommerce_version` option to `2.3.2`
- Load an admin page which will immediately trigger the update routine 
- Check out your memory usage and how many queries the plugin is doing

<img width="1510" alt="Screen Shot 2021-03-26 at 3 01 37 pm" src="https://user-images.githubusercontent.com/1892137/112577475-4ca90e00-8e44-11eb-9634-3aac72a06d9d.png">

## ✔️ Expected behavior
Plugin updates don't kill the WP Admin area.

## 🗃 Logs

TBA

**Comment by danielbitzer** [comment] 2021-03-26 05:31
My local development site now has 3,424 products and the 2.3.3 update routine is using 258 MB of memory 😬

**Comment by danielbitzer** [comment] 2021-03-26 05:39
We should consider min version of Woo we should support. If we can increase to WC 4.0 we could use ActionScheduler which would really help in solving this.

**Comment by danielbitzer** [comment] 2021-03-26 06:02
## My fix proposal:

1. Increase our min Woo version to > 4.0 so we can use ActionScheduler (importantly this is the version with custom tables) 🚀  (also then our min PHP version would be 7.0)
2. We use my [ActionScheduler jobs framework originally built for AutomateWoo](https://github.com/woocommerce/automatewoo/blob/develop/includes/Jobs/AbstractBatchedActionSchedulerJob.php) but has been [copied over to Google Listing and Ads](https://github.com/woocommerce/google-listings-and-ads/blob/trunk/src/Jobs/AbstractBatchedActionSchedulerJob.php)
3. We create an ActionScheduler batched job to split up the massive query in `\SkyVerge\WooCommerce\Facebook\Products\Sync::create_or_update_all_products` into separate batched job items

Also ideally the AS jobs framework would be converted into a composer package rather than coping the same code into every project we need background processing in.

**Comment by danielbitzer** [comment] 2021-03-26 06:58
@bb asked in Slack:

> is there some quick temporary fix that we can do or we need to go AS.

There could be a temporary fix but my question would be how hacky and rushed do we need to be? How urgent is the fix? Personally I think we should implement a robust fix. The alternative is relying on WP Cron scheduled events which could lead to different issues. E.g. users asking "why aren't my products syncing to facebook?"

One store that encountered this issue had 280,000 products. I really don't feel comfortable batching processing 280,000 items through WP Cron.

Also that this bug was already present because clicking the “Sync products” button that a user can click at anytime does the exact same thing as the 2.3.3 update routine.

**Comment by stuartduff** [comment] 2021-03-26 13:56
@danielbitzer I had an interaction recently with a user who was receiving a memory exhausted issue when the scheduler action of wc_facebook_regenerate_feed ran in v2.3.3. They indicated that we'd need to test with at least 3000 products on a store to replicate the behaviour.

They replied indicating that they disabled the “Default Google product category”. After doing so the Action Scheduler job to create the feed then completed the same job successfully without exhausting the memory!

They indicated this below too.

> The last working version is 2.1.4 and even then it required a 400MB single thread PHP limit which is very high.

The user also referenced this [Githhub Issue](https://github.com/woocommerce/facebook-for-woocommerce/issues/1704)

Not sure if it’s any help but I thought I’d feedback this info to you just in case :)

**Comment by budzanowski** [comment] 2021-03-26 14:00
I have analyzed the code and did some testing.

We have two issues here:
1) preparation of the whole catalog sync may exhaust the memory.
2) sync operation may exhaust memory.

### Analysis for 1)
It looks like the main query is OK in general. The problem is happening because we have queries inside the posts loop:
a. https://github.com/woocommerce/facebook-for-woocommerce/blob/7af84f0570939eed9d0aad607e27186eae93ce2f/includes/Products/Sync.php#L91
b. https://github.com/woocommerce/facebook-for-woocommerce/blob/7af84f0570939eed9d0aad607e27186eae93ce2f/includes/Products/Sync.php#L97

The a) query is the most problematic because it is called for each and every product that we have. Although this is a simple query triggering it multiple times is increasing memory consumption.
The b) query adds on top of that, how much - depends on the number of product variations.

We can get rid of both of them, I will have a PR for that part soon.

**Comment by budzanowski** [comment] 2021-03-26 14:00
@stuartduff
Thank you! Everything helps.

**Comment by budzanowski** [comment] 2021-03-26 15:09
I have identified that the code for finding all ids is also used in the feed generation. #1840 fixes this for both places.

**Comment by budzanowski** [comment] 2021-03-26 15:29
@danielbitzer This is already using Action Scheduler :) So we are good to go if you have an idea on how to approach the feed generation. For now I will figure out what else can we do.

**Comment by robertthegit** [comment] 2021-03-27 17:28
Hi there. Our site (4.8k products) has twice been effectively taken offline for half an hour or more by the plugin's sync processes in the last week - likely when the feed is generating. Our hosting company confirmed this as the source via analysis from New Relic (attached, they also say they're seeing many sites at the moment with this same issue). We're on 2.3.3 - the plugin is currently disabled until this is resolved (enabling it immediately slows down the site). Hope the attached helps diagnose...

<img width="952" alt="Screen Shot 2021-03-24 at 4 58 27 PM" src="https://user-images.githubusercontent.com/58297731/112728561-d37ee900-8f1f-11eb-8333-c9f17729b1dd.png">
<img width="600" alt="Screen Shot 2021-03-24 at 4 48 16 PM" src="https://user-images.githubusercontent.com/58297731/112728563-d679d980-8f1f-11eb-9e4a-cc1405b32f92.png">

**Comment by haszari** [comment] 2021-03-29 01:22
Split off two separate tasks for two fixes relating to this issue:

- #1842 Temporarily disable the full sync on upgrade. 
- #1841 Improve performance of full sync.

And also an enhancement request to improve the documentation around product sync: #1843

**Comment by budzanowski** [comment] 2021-04-01 07:09
Closing this in favour of tasks that @haszari has created.

**Closed by budzanowski** 2021-04-01 07:09 UTC
