### ISSUE TITLE
Product does not sync. when is edited.  and (Inventory quantity) goes from Any Number to ZERO

### ISSUE THREAD

**Issue by tecdisol** [woocommerce/facebook-for-woocommerce#2083] opened 2021-09-21 05:08 UTC
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the version of WordPress  5.8.1 , WooCommerce 5.6.0, and Facebook for WooCommerce 2.6.5.

## ✍️ Describe the bug
on (product catalogs of facebook)
screenshot:
https://liceoeduco-my.sharepoint.com/:i:/g/personal/a_liceo_edu_co/EetWuTBn2JtGossuKLW3BsMBR8R7tzBYAqug1L6xRP5qfw
do not automatically sync from WooCommerce to Facebook
when a product is edited.  and (Inventory quantity) goes from Any Number to ZERO.
screenshot
https://liceoeduco-my.sharepoint.com/:i:/g/personal/a_liceo_edu_co/ESxLF4DkjzxCvUrfeWUArhoB8Bit93eMg4DT6vexgpzmKg

## 🚶‍♀️ Steps to reproduce

1. create a product with (Inventory quantity) = 65
2. Product sync OK.
3. Edit the product with (Inventory quantity) = 0
4. Product does not sync. 

## ✔️ Expected behavior

change on (product catalogs of facebook) to NOT IS STOCK
screenshot:
https://liceoeduco-my.sharepoint.com/:i:/g/personal/a_liceo_edu_co/EX4GtYHlyaZCj5muMob8H0sBjLB0WU2F4wq_PwR8Oxhkzw

## 🗃 Logs

<details>

`
### WordPress Environment ###

WordPress address (URL): https://www.almacenflotablanca.com/web
Site address (URL): https://www.almacenflotablanca.com/web
WC Version: 5.6.0
REST API Version: ✔ 5.6.0
WC Blocks Version: ✔ 5.5.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.1
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.23
PHP Post Max Size: 516 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.78.0
OpenSSL/1.1.1l

SUHOSIN Installed: –
MySQL Version: 5.7.23-23
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.6.0
WC Database Prefix: wpaf_
Tamaño total de la base de datos: 25.14MB
Tamaño de los datos de la base de datos: 19.83MB
Tamaño del índice de la base de datos: 5.31MB
wpaf_woocommerce_sessions: Datos: 1.76MB + Índice: 0.06MB + Motor MyISAM
wpaf_woocommerce_api_keys: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpaf_woocommerce_attribute_taxonomies: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpaf_woocommerce_downloadable_product_permissions: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpaf_woocommerce_order_items: Datos: 0.03MB + Índice: 0.02MB + Motor MyISAM
wpaf_woocommerce_order_itemmeta: Datos: 0.20MB + Índice: 0.14MB + Motor MyISAM
wpaf_woocommerce_tax_rates: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpaf_woocommerce_tax_rate_locations: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpaf_woocommerce_shipping_zones: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpaf_woocommerce_shipping_zone_locations: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpaf_woocommerce_shipping_zone_methods: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpaf_woocommerce_payment_tokens: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpaf_woocommerce_payment_tokenmeta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpaf_woocommerce_log: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpaf_actionscheduler_actions: Datos: 1.52MB + Índice: 0.70MB + Motor InnoDB
wpaf_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpaf_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpaf_actionscheduler_logs: Datos: 1.52MB + Índice: 0.53MB + Motor InnoDB
wpaf_akeeba_common: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpaf_ak_params: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpaf_ak_profiles: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpaf_ak_stats: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpaf_ak_storage: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpaf_ak_users: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpaf_commentmeta: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpaf_comments: Datos: 0.14MB + Índice: 0.07MB + Motor MyISAM
wpaf_csshero4: Datos: 0.06MB + Índice: 0.00MB + Motor MyISAM
wpaf_epayco_order: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpaf_links: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpaf_options: Datos: 3.96MB + Índice: 1.18MB + Motor MyISAM
wpaf_postmeta: Datos: 6.89MB + Índice: 1.47MB + Motor MyISAM
wpaf_posts: Datos: 2.33MB + Índice: 0.42MB + Motor MyISAM
wpaf_termmeta: Datos: 0.03MB + Índice: 0.02MB + Motor MyISAM
wpaf_terms: Datos: 0.01MB + Índice: 0.02MB + Motor MyISAM
wpaf_term_relationships: Datos: 0.05MB + Índice: 0.12MB + Motor MyISAM
wpaf_term_taxonomy: Datos: 0.01MB + Índice: 0.01MB + Motor MyISAM
wpaf_usermeta: Datos: 0.16MB + Índice: 0.12MB + Motor MyISAM
wpaf_users: Datos: 0.01MB + Índice: 0.02MB + Motor MyISAM
wpaf_wc_admin_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpaf_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpaf_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpaf_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpaf_wc_download_log: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpaf_wc_gpf_render_cache: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpaf_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpaf_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wpaf_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wpaf_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpaf_wc_product_meta_lookup: Datos: 0.05MB + Índice: 0.07MB + Motor MyISAM
wpaf_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpaf_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpaf_wc_webhooks: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpaf_woocommerce_gpf_google_taxonomy: Datos: 0.86MB + Índice: 0.00MB + Motor MyISAM

### Post Type Counts ###

attachment: 1664
custom_css: 3
et_body_layout: 7
et_footer_layout: 1
et_header_layout: 1
et_pb_layout: 9
et_template: 8
et_theme_builder: 1
nav_menu_item: 145
page: 14
post: 4
product: 679
revision: 132
shop_order: 173
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

ePayco WooCommerce: por ePayco – 3.5.4
AJAX Search pra WooCommerce: por Damian Góra – 1.7.2
Akeeba Backup for WordPress: por Akeeba Ltd – 3.5.1
Child Theme Configurator: por Lilaea Media – 2.5.6
Departamentos y Ciudades de Colombia para Woocommerce: por Saul Morales Pacheco – 1.1.24
Divi Carousel: por DiviGear – 2.0.14
Duplicate Post: por Enrico Battocchi – 3.2.3
Facebook for WooCommerce: por Facebook – 2.6.5
Jetpack by WordPress.com: por Automattic – 8.8.3
Mantenimiento web: por Carlos Doral – 0.8
Product Filter for WooCommerce: por 7VX LLC
USA CA – 7.0.5

Woo Out Of Stock Products: por Andrew Gunn – 2.3
WooCommerce Advanced Shipping By Rules: por Open Tools
Reinhold Kainhofer – 2.0.6

WooCommerce PayU Latam Payment Gateway: por PayU Latam – 2.0
WooCommerce Google Product Feed: por Ademti Software Ltd. – 9.6.7 (la actualización a la versión 10.1.6 está disponible)
WooCommerce: por Automattic – 5.6.0

### Must Use Plugins (1) ###

akeeba-backup-coreupdate.php: por  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: COP ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Base de la tienda: #231529 - /tienda/
Carrito: #7 - /carrito/
Finalizar compra: #8 - /finalizar-compra/
Mi cuenta: #9 - /mi-cuenta/
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Almacen Flota Blanca - V 0.1
Version: 4.5.6.1604034378
Author URL: https://www.tecdisol.com/Colombia/Bienvenidos/es/
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 4.5.6
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce Google Product Feed options ###

Google merchant centre product feed: Enabled
Google merchant centre product review feed: -
Bing merchant centre feed: -
Google merchant centre local product inventory feed: -
Google merchant centre local products feed (legacy): -
Google merchant centre product inventory feed (legacy): -
Include variations in feed: Enabled
Send "item group ID": -
Expanded schema markup: -
Debug key: 9c799d6f-b56b-4f46-8157-bae428e78ca0

### WooCommerce Google Product Feed fields ###

Product description: Main product description (full preferred) plus variation description
Availability: Defaults to "in stock".
Brand: 
Manufacturer Part Number (MPN): 
Product Type: 
Google Product Category: 
Colour: Pre-populates from pa_color taxonomy.
Size system: 
Title: Pre-populates from product product_title.

### Action Scheduler ###

Completo: 5.247
Oldest: 2021-08-21 00:07:35 -0500
Newest: 2021-09-21 00:01:58 -0500

Pendiente: 1
Oldest: 2021-09-21 12:01:56 -0500
Newest: 2021-09-21 12:01:56 -0500

### Status report information ###

Generated at: 2021-09-21 00:06:42 -05:00
`

</details>

**Comment by sukafia** [comment] 2021-09-29 19:36
Hi @tecdisol, a product with an inventory quantity of "0" is out of stock, and out of stock products do not sync to Facebook. We have this documented [here](https://docs.woocommerce.com/document/facebook-for-woocommerce/facebook-for-woocommerce-products-are-not-displaying-in-facebook-shop/#out-of-stock-products)

I'll go ahead and close this issue as it's the intended behaviour and not a bug.

**Closed by sukafia** 2021-09-29 19:36 UTC

**Comment by tecdisol** [comment] 2021-10-02 16:57
> aviour

i consider it is do a but.
because i need it to be quantity of "0"
also on facebook.

otherwise  i will sell products i dont have.
