### ISSUE TITLE
Recent update breaks Facebook Pixel code

### ISSUE THREAD

**Issue by sukafia** [woocommerce/facebook-for-woocommerce#2534] opened 2023-05-02 21:18 UTC
## ✍️ Describe the bug

Facebook pixel code isn't working in the recent versions of Facebook for WooCommerce.

## 🚶‍♀️ Steps to reproduce

1. Update to the latest version
2. Check pixel event via [Meta pixel helper](https://developers.facebook.com/docs/meta-pixel/support/pixel-helper/)
3. Notice the pixel stopped working for pageview, add to cart and checkout events. 

## ✔️ Expected behavior

Pixel should continue working. 

## Additional info

Before the update:

![g0bnVc.png](https://user-images.githubusercontent.com/60121732/235786976-43f6dfef-682f-48ed-a696-1e67254ec207.png)

After the update:

![Smfy5M.png](https://user-images.githubusercontent.com/60121732/235786869-2d636f37-7f67-47b1-b9c1-4b4d37f440ec.png)

I found the issue also exists on v3.0.20. During my test, the issue could be resolved by downgrading to 3.0.19.

**Comment by sukafia** [comment] 2023-05-02 21:29
Reported [here](https://wordpress.org/support/topic/hi-guys-your-last-update-3-0-21-2023-05-02-is-breaking-the-pixel-code).

**Comment by sukafia** [comment] 2023-05-23 21:21
This issue has returned:

![GSWMzv.png](https://github.com/woocommerce/facebook-for-woocommerce/assets/60121732/ee01cd00-9b1f-42b0-a6da-dbaa44e7ecea)

Perhaps it's related to the last update.

**Comment by rawdreeg** [comment] 2023-05-24 08:21
Thanks for the report, @sukafia.

I can't reproduce it on my side. I went on `https://hmmmanothertest.mystagingwebsite.com/` and the pixel work fine as far as the code is concerned:

![Screenshot 2023-05-24 at 10 08 19](https://github.com/woocommerce/facebook-for-woocommerce/assets/4209011/a36953c5-999d-4490-878b-855d9a79bc3f)

Although the site is running the v3.0.22.

I tested with v3.0.23:

![Screenshot 2023-05-24 at 10 10 19](https://github.com/woocommerce/facebook-for-woocommerce/assets/4209011/3bc00491-b95f-4983-a4ce-f9530bf1f275)

And other event work too:

![Screenshot 2023-05-24 at 10 07 19](https://github.com/woocommerce/facebook-for-woocommerce/assets/4209011/f5c30aec-67ff-4e94-8637-7f2306922faf)

**Comment by rawdreeg** [comment] 2023-05-29 10:24
@sukafia I will close this as we can not reproduce the report.

**Closed by rawdreeg** 2023-05-29 10:24 UTC
Labels: priority: high, type: bug
