### ISSUE TITLE
Facebook Connection Issue

### ISSUE THREAD

**Issue by daniyalahmadk** [woocommerce/facebook-for-woocommerce#2154] opened 2022-02-15 15:06 UTC
## 🔎 Isolate the bug
- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
Facebook throws the following error when we try to connect with the plugin:

`Whoops, looks like something went wrong.`

This issue appears when we get back from Facebook and appears on the following link:

https://connect.woocommerce.com/auth/facebook

## 🚶‍♀️ Steps to reproduce
1. Go to Marketing > Facebook and click on Connect with Facebook.
2. Proceed with the all the steps on Facebook and click on Done button:
<img width="639" alt="image" src="https://user-images.githubusercontent.com/13753012/154089173-9cecb0e3-ad74-45f5-bec2-fae2e7b9e924.png">
3. Once done it will you to the following URL:

https://connect.woocommerce.com/auth/facebook/?code=XXXX

with the following error message:

`Whoops, looks like something went wrong.
`
## ✔️ Expected behavior
It shouldn't throw this error and should redirect without any error.

## Screenshot:

<img width="660" alt="image" src="https://user-images.githubusercontent.com/13753012/154088613-a59436ac-c95e-4174-8881-94644f7caf06.png">

**Comment by Aron0712** [comment] 2022-02-15 21:27
Hi,
Are there any updates on this? 
I tried to reconnect app to Facebook today and got the same whoops screen at the end, even though the integration part was created in Facebook side itself, but the app does not connects...

**Comment by floracolada** [comment] 2022-02-16 12:29
Hi, 
Are there any updates  ? 
I also do have the same problem. 
Thank you.

**Comment by atomictt** [comment] 2022-02-16 14:40
any updates on this?

**Comment by ghsgabriel** [comment] 2022-02-16 15:02
Same issue

**Comment by Farboudfhk** [comment] 2022-02-16 17:35
Same problem!

**Comment by aquiilamendes** [comment] 2022-02-16 18:54
Same problem, I'm following it on Github as informed, what an annoying situation, we can't work with ads or product tagging due to this problem.

**Comment by davidalzate** [comment] 2022-02-16 21:48
hi, I have the same issue, we have 3 big stores on woocommerce that need to get connected with FB, please share an update. thanks.

**Comment by imachequa** [comment] 2022-02-16 21:59
+1 ... this issue is already to old and should had been solved already.  Please keep some updates on the issue

**Comment by r3markableNL** [comment] 2022-02-16 22:49
Got exactly the same problem since yesterday! Allready tried everything i could find on the form, but nothing seems to help. Can someone please help

**Comment by galbaras** [comment] 2022-02-17 02:13
Why is this even going through woocommerce.com?!

**Comment by andresdandrea** [comment] 2022-02-17 03:40
Hi, I'm having the same issue... Exactly as described. Not using a default WordPress or WooCommerce theme, though... Premium WooCommerce Theme properly licensed and registered.

**Comment by galbaras** [comment] 2022-02-17 05:32
Just to confirm, I downloaded the plugin from wp.org, NOT from woocommerce.com, but there's a valid WooCommerce connection and an active subscription of a premium plugin.

**Comment by Farboudfhk** [comment] 2022-02-17 06:25
Maybe someone will find a way: I change the value from the database/wp_options/wc_facebook_external_business_id:"xxxxxx", the error also changes

**Comment by lamebg** [comment] 2022-02-17 09:07
Same issue. My connection between wordpress and fb was working great, but fb is a mess. There many problems with manage the items and catalogs...and so so so...no need to talk for fb problems...and I just delete the connection to rebiuld the products and voala....I am here now....but I am mad cuz more and more dev don't take time for tests...

anyway

we are waiting...

**Comment by Ceballos12** [comment] 2022-02-17 18:01
I've been dealing with this problem all day

Any news?

**Comment by galbaras** [comment] 2022-02-18 00:58
> Maybe someone will find a way: I change the value from the database/wp_options/wc_facebook_external_business_id:"xxxxxx", the error also changes

Changes to what? No error or a different error?

Also, what's `xxxxxx`? Is it the token from the URL? If not, where do we get it?

Is there anyone in this discussion from the development or plugin support team?

**Comment by Farboudfhk** [comment] 2022-02-18 12:43
> > Maybe someone will find a way: I change the value from the database/wp_options/wc_facebook_external_business_id:"xxxxxx", the error also changes
> 
> Changes to what? No error or a different error?
> 
> Also, what's `xxxxxx`? Is it the token from the URL? If not, where do we get it?
> 
> Is there anyone in this discussion from the development or plugin support team?

Change to Page Name or 13 String character
After changing that error change to : "Could not retrieve Facebook Business Extension System User"

**Comment by MarcMurrayUpfront** [comment] 2022-02-18 15:10
Having the same issue here folks, rendering the plugin totally unusable for new users.

**Comment by daramayo90** [comment] 2022-02-18 16:36
Same problem here, any news?

**Comment by ilyassbenabde** [comment] 2022-02-18 23:19
Same problem here, any news?

**Comment by banderas0138** [comment] 2022-02-19 13:39
same problem :/

**Comment by Foothills821** [comment] 2022-02-20 00:18
Same problem with me too.

**Comment by Exactpk** [comment] 2022-02-20 13:36
> ##  Isolate the bug
> * [x]  I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
> * [x]  I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.
> 
> ##  Describe the bug
> Facebook throws the following error when we try to connect with the plugin:
> 
> `Whoops, looks like something went wrong.`
> 
> This issue appears when we get back from Facebook and appears on the following link:
> 
> https://connect.woocommerce.com/auth/facebook
> 
> ##  Steps to reproduce
> 1. Go to Marketing > Facebook and click on Connect with Facebook.
> 2. Proceed with the all the steps on Facebook and click on Done button:
> 
> <img alt="image" width="639" src="https://user-images.githubusercontent.com/13753012/154089173-9cecb0e3-ad74-45f5-bec2-fae2e7b9e924.png">
> 
> 3. Once done it will you to the following URL:
> https://connect.woocommerce.com/auth/facebook/?code=XXXX
> 
> with the following error message:
> 
> `Whoops, looks like something went wrong. `
> 
> ##  Expected behavior
> It shouldn't throw this error and should redirect without any error.
> 
> ## Screenshot:
> <img alt="image" width="660" src="https://user-images.githubusercontent.com/13753012/154088613-a59436ac-c95e-4174-8881-94644f7caf06.png">





> ##  Isolate the bug
> * [x]  I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
> * [x]  I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.
> 
> ##  Describe the bug
> Facebook throws the following error when we try to connect with the plugin:
> 
> `Whoops, looks like something went wrong.`
> 
> This issue appears when we get back from Facebook and appears on the following link:
> 
> https://connect.woocommerce.com/auth/facebook
> 
> ##  Steps to reproduce
> 1. Go to Marketing > Facebook and click on Connect with Facebook.
> 2. Proceed with the all the steps on Facebook and click on Done button:
> 
> <img alt="image" width="639" src="https://user-images.githubusercontent.com/13753012/154089173-9cecb0e3-ad74-45f5-bec2-fae2e7b9e924.png">
> 
> 3. Once done it will you to the following URL:
> https://connect.woocommerce.com/auth/facebook/?code=XXXX
> 
> with the following error message:
> 
> `Whoops, looks like something went wrong. `
> 
> ##  Expected behavior
> It shouldn't throw this error and should redirect without any error.
> 
> ## Screenshot:
> <img alt="image" width="660" src="https://user-images.githubusercontent.com/13753012/154088613-a59436ac-c95e-4174-8881-94644f7caf06.png">

same Problem here: > with the following error message:
> 
> `Whoops, looks like something went wrong. `

**Comment by julonde** [comment] 2022-02-21 10:25
I think, this relates to this topic: (https://github.com/woocommerce/facebook-for-woocommerce/issues/2148)
When i tried out, what the problem could possible be, the error chanced from "Woopsie" to this issue in that thread above. Bun unfortunatly, the case is also open. :/ I really hope, that someone get the solution. It drives me crazy.

**Comment by rashedripon** [comment] 2022-02-21 13:35
4787823-zen reported the same

**Comment by galbaras** [comment] 2022-02-22 03:23
I've deactivated and removed the plugin, then reinstalled/activated it. This time, instead of choosing a catalog, which I suspected was in a different business account, I chose to create a new one, and the connection completed successfully.

Still, the level of support from the plugin team is appalling, and the fact that a woocommerce.com server is involved in this process is highly suspicious.

**Comment by aquiilamendes** [comment] 2022-02-22 12:44
> I've deactivated and removed the plugin, then reinstalled/activated it. This time, instead of choosing a catalog, which I suspected was in a different business account, I chose to create a new one, and the connection completed successfully.
> 
> Still, the level of support from the plugin team is appalling, and the fact that a woocommerce.com server is involved in this process is highly suspicious.

I did what you reported, deleted all catalogs and created a new one at the time of integration but I was not successful the error message was the same "Whoops"

**Comment by simonhancock777** [comment] 2022-02-22 15:59
Same issue here. All was working fine, I was advised to disconnect the account and re-connect to resolve another issue and now it just won't connect. Tried all options but nothing. Very frustrating

**Comment by atomictt** [comment] 2022-02-22 17:51
just saw a plugin update. thought i give it a go, updated it and my fb plugin is reconnected once again. currently running additional tests.

**Comment by daramayo90** [comment] 2022-02-22 18:08
It's working now guys

**Comment by franksierra** [comment] 2022-02-22 19:16
I can confirm. this is fixed after updating to 2.6.10 release

**Comment by aquiilamendes** [comment] 2022-02-22 20:05
It didn't work for me, but it changed the error. When I click finish in the facebook permissions dialog it returns this message.

**Could not retrieve Facebook Business Extension System User**

**Comment by matecocidocontortafritas** [comment] 2022-02-22 21:19
hola, sigo teniendo este resultado cuando intento conectar

_Could not retrieve Facebook Business Extension System User_

**Comment by aquelino** [comment] 2022-02-23 00:55
Atualizei o plugin e o woocomerce funcionou

**Comment by simonhancock777** [comment] 2022-02-23 11:07
All working for me now, thanks for the updates

**Comment by aquiilamendes** [comment] 2022-02-23 13:22
Nothing for me so far, I made all the disconnections, deleted everything old such as catalog, pixel, business account that I had already approved and when following the integration dialog boxes at the end, it returns the message I already sent:

**Could not retrieve Facebook Business Extension System User**

![Captura de tela 2022-02-23 101937](https://user-images.githubusercontent.com/99833627/155327629-74793ce1-9cc0-41d8-bb5b-c67483eadafb.jpg)
![Captura de tela 2022-02-23 101951](https://user-images.githubusercontent.com/99833627/155327633-eb79c535-0107-4b1c-9021-9da287d44a9c.jpg)
![Captura de tela 2022-02-23 102001](https://user-images.githubusercontent.com/99833627/155327638-8e952956-516d-4561-8452-5f75001749b0.jpg)
![Captura de tela 2022-02-23 102016](https://user-images.githubusercontent.com/99833627/155327639-57188779-1ab0-4595-bb87-02271caff639.jpg)
![Captura de tela 2022-02-23 102030](https://user-images.githubusercontent.com/99833627/155327641-bede5a65-19e1-47f0-821e-7b71ceaa1a52.jpg)
![Captura de tela 2022-02-23 102039](https://user-images.githubusercontent.com/99833627/155327643-4424bc00-af38-4ca5-b8a3-643f97a8d19f.jpg)
![Captura de tela 2022-02-23 102053](https://user-images.githubusercontent.com/99833627/155327644-74a3456e-7cec-48f3-95d4-4fa45d05b7e9.jpg)
![Captura de tela 2022-02-23 102109](https://user-images.githubusercontent.com/99833627/155327646-72267d7f-ff14-4ee0-b20c-9baa2867a960.jpg)
![Captura de tela 2022-02-23 102118](https://user-images.githubusercontent.com/99833627/155327649-3e2aa047-7429-43dc-b578-c849bb1d0ab6.jpg)
![Captura de tela 2022-02-23 102128](https://user-images.githubusercontent.com/99833627/155327650-edc6ddf0-dac8-4c70-9072-b1eac3744ac3.jpg)
![Captura de tela 2022-02-23 102141](https://user-images.githubusercontent.com/99833627/155327652-4c10bc7a-22e6-42cc-938b-f5ffffe55a94.jpg)
![Captura de tela 2022-02-23 102155](https://user-images.githubusercontent.com/99833627/155327655-8e2c645d-74c3-44a1-a4f2-3af9e86cf77b.jpg)

**Comment by r3markableNL** [comment] 2022-02-23 13:49
Updated the plugin and it F I N A L L Y works!

**Comment by Ceballos12** [comment] 2022-02-24 12:44
Great news! i don't have a plugin updates available but i'll try anyway

**Comment by Ceballos12** [comment] 2022-02-24 12:48
ITS WORSSSS!

[works](https://user-images.githubusercontent.com/99908004/155526908-ff8b0d66-a269-4523-ac54-45e671df7672.PNG)

**Comment by budzanowski** [comment] 2022-03-01 10:16
Closing this as the `Woops, looks like something went wrong issue has been` fixed. The other connection issues are tracked in  https://github.com/woocommerce/facebook-for-woocommerce/issues/2148

**Closed by budzanowski** 2022-03-01 10:16 UTC
Labels: priority: high, type: bug
