### ISSUE TITLE
woocommerce plugin errors in debug log

### ISSUE THREAD

**Issue by GlynLewis** [woocommerce/facebook-for-woocommerce#1552] opened 2020-09-16 02:09 UTC
[16-Sep-2020 01:54:48 UTC] PHP Notice:  Trying to get property 'post_status' of non-object in /home/techrcxm/catkarmacreations.com/wp-content/plugins/facebook-for-woocommerce/includes/fbproductfeed.php on line 455
[16-Sep-2020 01:54:48 UTC] PHP Notice:  Trying to get property 'post_status' of non-object in /home/techrcxm/catkarmacreations.com/wp-content/plugins/facebook-for-woocommerce/includes/fbproductfeed.php on line 455
[16-Sep-2020 01:54:48 UTC] PHP Notice:  Trying to get property 'post_status' of non-object in /home/techrcxm/catkarmacreations.com/wp-content/plugins/facebook-for-woocommerce/includes/fbproductfeed.php on line 455
[16-Sep-2020 01:54:48 UTC] PHP Notice:  Trying to get property 'post_status' of non-object in /home/techrcxm/catkarmacreations.com/wp-content/plugins/facebook-for-woocommerce/includes/fbproductfeed.php on line 455
[16-Sep-2020 01:54:48 UTC] PHP Notice:  Trying to get property 'post_status' of non-object in /home/techrcxm/catkarmacreations.com/wp-content/plugins/facebook-for-woocommerce/includes/fbproductfeed.php on line 455
[16-Sep-2020 01:54:48 UTC] PHP Notice:  Trying to get property 'post_status' of non-object in /home/techrcxm/catkarmacreations.com/wp-content/plugins/facebook-for-woocommerce/includes/fbproductfeed.php on line 455
[16-Sep-2020 01:54:49 UTC] PHP Notice:  Trying to get property 'post_status' of non-object in /home/techrcxm/catkarmacreations.com/wp-content/plugins/facebook-for-woocommerce/includes/fbproductfeed.php on line 455
[16-Sep-2020 01:54:49 UTC] PHP Notice:  Trying to get property 'post_status' of non-object in /home/techrcxm/catkarmacreations.com/wp-content/plugins/facebook-for-woocommerce/includes/fbproductfeed.php on line 455
[16-Sep-2020 01:54:49 UTC] PHP Notice:  Trying to get property 'post_status' of non-object in /home/techrcxm/catkarmacreations.com/wp-content/plugins/facebook-for-woocommerce/includes/fbproductfeed.php on line 455
[16-Sep-2020 01:54:49 UTC] PHP Notice:  Trying to get property 'post_status' of non-object in /home/techrcxm/catkarmacreations.com/wp-content/plugins/facebook-for-woocommerce/includes/fbproductfeed.php on line 455
[16-Sep-2020 01:54:49 UTC] PHP Notice:  Trying to get property 'post_status' of non-object in /home/techrcxm/catkarmacreations.com/wp-content/plugins/facebook-for-woocommerce/includes/fbproductfeed.php on line 455
[16-Sep-2020 01:54:49 UTC] PHP Notice:  Trying to get property 'post_status' of non-object in /home/techrcxm/catkarmacreations.com/wp-content/plugins/facebook-for-woocommerce/includes/fbproductfeed.php on line 455
[16-Sep-2020 01:54:49 UTC] PHP Notice:  Trying to get property 'post_status' of non-object in /home/techrcxm/catkarmacreations.com/wp-content/plugins/facebook-for-woocommerce/includes/fbproductfeed.php on line 455
[16-Sep-2020 01:54:49 UTC] PHP Notice:  Trying to get property 'post_status' of non-object in /home/techrcxm/catkarmacreations.com/wp-content/plugins/facebook-for-woocommerce/includes/fbproductfeed.php on line 455

**Comment by simonporter007** [comment] 2020-10-08 12:51
Hi @GlynLewis,

Thanks for reporting this issue! Do you have any custom product types created in your store?

From the error you've referenced, it looks as though the list of prouct_ids that the plugin gathered when searching for all '_product_' and '_product_variation_' types returned something that wasn't expected. As when it then tries to check the post_status on these objects, it fails.

If you'd like to help track this down further, as this seems to be specific to your stores configuration as we don't see this locally, it would be great if you could add additional logging on line 455 of fbproductfeed.php. If we could see what object it was trying to work with at the time of the error, that would give us something more to investigate!

You can use the plugins own logging function if you'd like, I would suggest adding:
`facebook_for_woocommerce()->log( 'DEBUG: Looping over parent of: ' . $post_id );` on line 455 of fbproductfeed.php and then seeing at which ID the error is thrown.

Could you let me know if you have a moment to try this out?

Cheers!

Simon.

**Comment by simonporter007** [comment] 2020-11-06 13:36
Hey @GlynLewis,

We haven't heard from you in a while, so let me close this issue. I hope that the previous suggestion was helpful and if you were able to gather any more debug information that would help narrow this down, that would be super useful! So please do let us know.

Cheers,

**Comment by laurentdebricon** [comment] 2020-12-08 09:08
Hello, i am also having the same issue. i added the debug log you suggest @simonporter007 , 
sadly it's not that simple : 
in the facebook log now i have 
```
12-08-2020 @ 01:03:26 - DEBUG: Looping over parent of: 24762
12-08-2020 @ 01:03:26 - DEBUG: Looping over parent of: 24761
12-08-2020 @ 01:03:26 - DEBUG: Looping over parent of: 24760
12-08-2020 @ 01:03:26 - DEBUG: Looping over parent of: 24759
12-08-2020 @ 01:03:26 - DEBUG: Looping over parent of: 24758
12-08-2020 @ 01:03:26 - DEBUG: Looping over parent of: 24757
12-08-2020 @ 01:03:26 - DEBUG: Looping over parent of: 24756
```

and in my wordpress log
```
[08-Dec-2020 08:47:53 UTC] PHP Notice:  Trying to get property 'post_status' of non-object in /var/www/html/wp-content/plugins/facebook-for-woocommerce/includes/fbproductfeed.php on line 457
```

if you could suggest me a better logging technique// tricks to help debug this issue that i am having for one year, i'll do it.
best regards

**Comment by laurentdebricon** [comment] 2020-12-08 09:57
ok , i figured it out with a better debug message with a condition 

```
	$tmp_var = get_post( wp_get_post_parent_id( $post_id ));

	if(empty( $tmp_var )){
		facebook_for_woocommerce()->log( 'DEBUG: Looping over empty parent of: ' . $post_id );
	}
```

Now i have a new list of post id

```
12-08-2020 @ 10:49:11 - DEBUG: Looping over empty parent of: 8103
12-08-2020 @ 10:49:11 - DEBUG: Looping over empty parent of: 8097
12-08-2020 @ 10:49:11 - DEBUG: Looping over empty parent of: 8087
12-08-2020 @ 10:49:11 - DEBUG: Looping over empty parent of: 8079
12-08-2020 @ 10:49:11 - DEBUG: Looping over empty parent of: 7805
12-08-2020 @ 10:49:11 - DEBUG: Looping over empty parent of: 7344
12-08-2020 @ 10:49:11 - DEBUG: Looping over empty parent of: 7304
12-08-2020 @ 10:49:11 - DEBUG: Looping over empty parent of: 7301
12-08-2020 @ 10:49:11 - DEBUG: Looping over empty parent of: 5486
12-08-2020 @ 10:49:11 - DEBUG: Looping over empty parent of: 5260

```

then what to do ? :D

**Comment by SiobhyB** [comment] 2021-01-04 09:31
@simonporter007, would we be able to re-open this issue? We have another report on the forums [here](https://wordpress.org/support/topic/error-in-debug-log-18/) and @laurentdebricon has gone through the requested debugging steps. Are there any other steps that would be helpful in isolating this issue?

**Comment by SiobhyB** [comment] 2021-01-06 10:38
@laurentdebricon, thank you for taking the time to enable that extra logging and for sharing your findings!

As a next step, could you take a look at the products with those IDs? It's worth investigating why/how a variation has a missing/empty parent product. For example, is it some custom product type or is it a standard variable product?

It seems like there may be some customization or a specific plugin that creates product variations in a way that doesn't assign a parent product. If we can narrow down what type of product variations/products it’s working with when the error occurs, we can see how we can guide you from there.

Although we don't officially provide support via GitHub, we'd be happy to continue helping if you can create a new forum post on [our support forum here](https://wordpress.org/support/plugin/facebook-for-woocommerce/).

**Comment by haszari** [comment] 2021-04-16 01:04
Closing as there's been no new updates to this for a few months. If you can reproduce the problem on a minimal Woo site with  no other plugins, please open a new issue with details of how to reproduce the bug. Thanks 😃

**Closed by haszari** 2021-04-16 01:04 UTC
