### ISSUE TITLE
Facebook Woocommerce integration problem

### ISSUE THREAD

**Issue by mertnizamoglu** [woocommerce/facebook-for-woocommerce#2131] opened 2021-12-14 16:04 UTC
I made the necessary adjustments via facebook. I made the connection through Woocommerce without any problems. However, although my products do not come to the specified catalogue, I am getting a result as indicated in the image on my Woocommerce Facebook homepage. Why am I getting such a result? 
![facebook1](https://user-images.githubusercontent.com/44955710/146034499-127b4881-674e-4c1f-be9c-af090676946a.jpg)

**Comment by jconroy** [comment] 2022-02-28 03:08
Closing as a duplicate of the newer https://github.com/woocommerce/facebook-for-woocommerce/issues/2139 (going off the screenshot)

**Closed by jconroy** 2022-02-28 03:08 UTC
