### ISSUE TITLE
Critical Error on Wordpress

### ISSUE THREAD

**Issue by stevefettis** [woocommerce/facebook-for-woocommerce#2162] opened 2022-02-23 13:19 UTC
Hi,

I recently uploaded this to my site, also running Facebook for Wordpress. Whenever i activate FB for woocommerce, I'm getting a critical error on my site, unable to access the dashboard, I'm having to go to my hosting company to take the plugin back off. I've rolled it back to a previous release (2.6.9) and it still gave me the error. Does anyone know how to resolve this?

**Comment by frndorios** [comment] 2022-02-23 19:25
Hi, i also have the same problem.. did you solve it?

**Comment by wojsmol** [comment] 2022-02-23 19:55
Hi all
@stevefettis Please replace pluginm with version 2.6.10 and then see temporary fix in [#](https://github.com/woocommerce/facebook-for-woocommerce/issues/2157)
@frndorios Also see fix in https://github.com/woocommerce/facebook-for-woocommerce/issues/2157
If this fixes the issue then please report you environment in https://github.com/woocommerce/facebook-for-woocommerce/issues/2157

**Comment by jconroy** [comment] 2022-02-28 02:12
Going to assume this is a duplicate of https://github.com/woocommerce/facebook-for-woocommerce/issues/2157 and close. If not please comment with some more details of the error you are receiving.

**Closed by jconroy** 2022-02-28 02:12 UTC
