### ISSUE TITLE
Integrate WOOCOMMERCE REST API w/ Facebook Sync Product

### ISSUE THREAD

**Issue by bmardock** [woocommerce/facebook-for-woocommerce#244] opened 2018-01-30 20:56 UTC
When creating products through the Woocommerce Rest API Product does not Sync to Facebook.
In order to Sync to Facebook requires going into the product edit page and click update on each product.

Which action should be triggered after Creating a product through Woocommerce Rest API.

**Comment by mengyingdu** [comment] 2018-01-31 02:22
Hi @bmardock ,

To create a product, we add action [here](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/facebook-commerce.php#L207-L228). I don't think the rest api approach will reach this line.

**Comment by bmardock** [comment] 2018-01-31 17:45
Also when trying to sync products via admin from : 
Woocommerce > Integration > Facebook Integration 

The status shows:
Status: Products are synced to Facebook.

Is there any work around you guys can recommend other then manually updating each product from the admin edit?

**Comment by dmitridr** [comment] 2018-02-13 22:48
Hi,

Thanks for reporting this. There may be a hook we can add so that the rest API also updates the products. I'm not sure where that is, but we can probably figure it out and add it, though I've marked this as help-wanted since I don't think we will get to this soon.

I would recommend doing `Force Resync` after a large # of API updates, this should pick up any new products added through the API.

**Comment by bmardock** [comment] 2018-03-31 03:32
I recently updated my product save functionality to use Wordpress's wp_insert_post and update_post_meta methods vs the Rest API(way faster). However I still have the same issue of not being able to trigger the facebook id.

**Comment by mengyingdu** [comment] 2018-06-27 23:09
We'll consider to build support for REST API  based on user demand and Engineer capacity, if anyone like this feature please vote here to help us understand priority. Unfortunately, we don't have the ETA now.

If anyone is interested, we'd be happy to review any pull request to add this functionality!

**Comment by mengyingdu** [comment] 2018-07-26 21:41
@bmardock 
If you can trigger this [hook](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/facebook-commerce.php#L207-L228)
But it needs a global post id, so i don't think you can trigger that outside of the UI. 

If you actually make it, would like to hear your sharing.

Thanks.

**Comment by bmardock** [comment] 2018-07-27 16:09
@mengyingdu Correct. This isn't exposed outside of the UI to my knowledge.
I was looking into if this could be triggered through admin-ajax.

**Comment by mengyingdu** [comment] 2018-07-27 23:41
Welcome to send us a pull request if you make it!

**Comment by budzanowski** [comment] 2022-09-07 16:30
This issue is stale. We don't have more requests for this feature. If something changes and this feature will be more desirable we will revisit this. The cyclic sync in the plugin should sync the products, not mediately though.

**Closed by budzanowski** 2022-09-07 16:30 UTC
Labels: help wanted, type: enhancement, feature: product sync

**Comment by schweini** [comment] 2023-04-21 22:43
This bug is still buggy. Price updates via the Woocommerce REST API still don't trigger Facebook Sync's update, but manually going to the product in woocommerce, and hitting the 'update' button, does.

Could we at least have some API endpoint to fire whatever event you guys are monitoring to detect updates to a product? Or, worst case, that we could trigger the 'sync all' button via REST?

**Comment by thekntl** [comment] 2023-07-12 10:38
I think this is not a bug but it is a missing feature.

At least if you add a Rest API support for this plugin.
So we can trigger Facebook Sync on product updates.

**Comment by esalonico** [comment] 2026-01-07 17:14
Any updates on this?
