### ISSUE TITLE
'Added an item to their shop' appearing in people's newsfeeds

### ISSUE THREAD

**Issue by slg597** [woocommerce/facebook-for-woocommerce#1724] opened 2020-12-08 01:16 UTC
For some reason, I am constantly getting posts in my newsfeed from my business page saying '... added an item to their shop' with a random product. It is reaching hundreds of people and I am scared people will start unfollowing the page if they keep getting them on their newsfeed. I can't figure out why it is always happening. I have tried disconnecting and reconnecting and it just seems to happen again. How can I stop this from automatically posting?

**Comment by ecaron** [comment] 2020-12-09 20:52
We're in the same boat. Facebook support has confirmed/pointed/blamed that the problem is coming from this plugin.

**Comment by jbaekz** [comment] 2020-12-11 10:07
Confirming we're facing the same issue. Really frustratiing. 

What is even worse is that we're using a 3. party service to keep stock status up-to-date across a physical store and an online store. 
All product creation is handled from the physical store and pushed to the WooCommerce installation. Facebook shows notifications about added products when they're not yet published i.e. when they're in draft status in WooCommerce.

**Comment by Waleedov** [comment] 2021-09-18 20:43
I have the same issue, using woocomerce integration. Any solution yet?

**Comment by solstudioim** [comment] 2022-03-16 11:00
Looks like it's not on the plugin side.

This has been reported before elsewhere with different commerce integration platform. Users of other Facebook Integration for like Shopify and Square have experienced the same thing as reported **[here](https://community.shopify.com/c/shopify-discussions/facebook-followers-seeing-posts-quot-shop-name-added-an-item-to/td-p/952187#:~:text=I%20signed%20up,gotten%20no%20response.)** and **[here](https://community.shopify.com/c/shopify-discussions/facebook-followers-seeing-posts-quot-shop-name-added-an-item-to/td-p/952187/page/3#:~:text=This%20is%20NOT%C2%A0%20a%20Shopify%20issue.%C2%A0%20It%20is%20a%20FACEBOOK%20issue.%C2%A0%20I%20use%20Square%20(not%20Shopify)%20and%20have%20the%20same%20problem.%C2%A0%20No%20setting%20in%20Square%20or%20Shopify%20is%20going%20to%20fix%20it.%C2%A0%20Facebook%20is%20automatically%20doing%20this%20with%20no%20option%20to%20turn%20it%20off.)**

Also, Facebook support **[confirmed](https://community.shopify.com/c/shopify-discussions/facebook-followers-seeing-posts-quot-shop-name-added-an-item-to/td-p/952187/page/3#:~:text=This%20is%20NOT%C2%A0%20a%20Shopify%20issue.%C2%A0%20It%20is%20a%20FACEBOOK%20issue.%C2%A0%20I%20use%20Square%20(not%20Shopify)%20and%20have%20the%20same%20problem.%C2%A0%20No%20setting%20in%20Square%20or%20Shopify%20is%20going%20to%20fix%20it.%C2%A0%20Facebook%20is%20automatically%20doing%20this%20with%20no%20option%20to%20turn%20it%20off.)** that it's a feature that's being tested by Facebook.

**Comment by rawdreeg** [comment] 2022-06-30 08:37
Based on @solstudioim [comment](https://github.com/woocommerce/facebook-for-woocommerce/issues/1724#issuecomment-1068998902), I will close this issue. Thanks

R

**Closed by rawdreeg** 2022-06-30 08:37 UTC
Labels: priority: high, type: bug, feature: product sync
