### ISSUE TITLE
Placeholder for events through Ajax is always triggered

### ISSUE THREAD

**Issue by engineerized** [woocommerce/facebook-for-woocommerce#1279] opened 2020-05-12 08:24 UTC
- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
In file location facebook-for-woocommerce/facebook-commerce-pixel-event.php
```
<!-- %s Facebook Integration Begin -->
%s
<script>
%s
fbq( 'track', 'PageView', %s );

document.addEventListener( 'DOMContentLoaded', function() {
	jQuery && jQuery( function( $ ) {

		// insert placeholder for events injected when a product is added to the cart through Ajax
		$( document.body ).append( '**<div class=\"wc-facebook-pixel-event-placeholder\"></div>**' );
	} );
}, false );

</script>
<!-- DO NOT MODIFY -->
<!-- %s Facebook Integration end -->
```

##🚶‍♀️ Steps to reproduce

The placeholder `<div class="wc-facebook-pixel-event-placeholder"></div>` is always visible in the body tag no matter if Ajax "Add to cart" button is clicked or not.

Make sure that when Ajax is used that add to cart event is working properly by fixing this bug.

## ✔️ Expected behavior
This placeholder <div class=\"wc-facebook-pixel-event-placeholder\"></div> should only be triggered when adding product to cart via Ajax and "AddToCart" event should be triggered.

**Comment by haszari** [comment] 2021-04-16 01:20
Hi there @engineerized - thanks for reporting. Based on your description, I don't see an issue here - that `<div>` should not trigger any events, it looks like a placeholder.

If you're seeing a bug relating to this, please add more details so we can reproduce:

- Detailed steps for how to reproduce the issue.
- What you expected, and what you saw - i.e. details of the bug behaviour.
- Bonus points: how this impacts your store/business, or what you are trying to do.

Thank you 🙂

**Comment by rawdreeg** [comment] 2022-09-07 21:08
Based on hazsari comments. I am closing this.

**Closed by rawdreeg** 2022-09-07 21:08 UTC
Labels: needs feedback
