### ISSUE TITLE
Error when I try to create or edit products and categories

### ISSUE THREAD

**Issue by kunaqeduardo** [woocommerce/facebook-for-woocommerce#1680] opened 2020-11-05 02:27 UTC
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

The error is happening from 2020.10.26 - VERSION 2.1.0 with inclusion of Google Categories
When I try to edit one of my products or my categories through "edit" option the website gives me a 500 error.
The same error occurs when I try to create a new category or product in my store.
Everything works fine when I set off the Facebook for woocommerce plug-in

I don't have any problem to edit or create new post, pages or categories in the wordpress "blog" area. It's only happening in the woocommerce area.

##🚶‍♀️ Steps to reproduce

1. Go to the product menu and click on add new product 

1. Go to product menu and click on All products
2. Click on the "Edit" option of any product

1. Go to product menu and click on Categories
2. Click on the "Edit" option of any category / Click on the "add new category" option 

## ✔️ Expected behavior

Get in the Create / edit product page
Get in the create / edit category page

## 🗃 Logs

`
### WordPress Environment ###

WordPress address (URL): https://mi-salud-integral.com
Site address (URL): https://mi-salud-integral.com
WC Version: 4.6.1
REST API Version: ✔ 4.6.1
WC Blocks Version: ✔ 3.4.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.2
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.9
PHP Post Max Size: 32 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.49-cll-lve
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.6.1
WC Database Prefix: wp_
Tamaño total de la base de datos: 58.94MB
Tamaño de los datos de la base de datos: 46.17MB
Tamaño del índice de la base de datos: 12.77MB
wp_woocommerce_sessions: Datos: 6.81MB + Índice: 0.34MB + Motor MyISAM
wp_woocommerce_api_keys: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_woocommerce_attribute_taxonomies: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_woocommerce_downloadable_product_permissions: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_woocommerce_order_items: Datos: 0.15MB + Índice: 0.07MB + Motor MyISAM
wp_woocommerce_order_itemmeta: Datos: 2.01MB + Índice: 0.64MB + Motor MyISAM
wp_woocommerce_tax_rates: Datos: 0.01MB + Índice: 0.01MB + Motor MyISAM
wp_woocommerce_tax_rate_locations: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_woocommerce_shipping_zones: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_woocommerce_shipping_zone_locations: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_woocommerce_shipping_zone_methods: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_woocommerce_payment_tokens: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_woocommerce_payment_tokenmeta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_woocommerce_log: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_actionscheduler_actions: Datos: 1.92MB + Índice: 0.47MB + Motor MyISAM
wp_actionscheduler_claims: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_actionscheduler_groups: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wp_actionscheduler_logs: Datos: 0.95MB + Índice: 0.64MB + Motor MyISAM
wp_adtribes_my_conversions: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_commentmeta: Datos: 0.12MB + Índice: 0.05MB + Motor MyISAM
wp_comments: Datos: 0.48MB + Índice: 0.16MB + Motor MyISAM
wp_eg_grids: Datos: 0.01MB + Índice: 0.01MB + Motor MyISAM
wp_eg_item_elements: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_eg_item_skins: Datos: 0.12MB + Índice: 0.01MB + Motor MyISAM
wp_eg_navigation_skins: Datos: 0.03MB + Índice: 0.01MB + Motor MyISAM
wp_ewwwio_images: Datos: 1.56MB + Índice: 0.49MB + Motor MyISAM
wp_ewwwio_queue: Datos: 0.01MB + Índice: 0.01MB + Motor MyISAM
wp_failed_jobs: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_links: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_mailchimp_carts: Datos: 0.07MB + Índice: 0.00MB + Motor MyISAM
wp_mailchimp_jobs: Datos: 0.01MB + Índice: 0.00MB + Motor MyISAM
wp_ms_snippets: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_options: Datos: 5.43MB + Índice: 0.18MB + Motor MyISAM
wp_packlink_entity: Datos: 6.48MB + Índice: 0.12MB + Motor MyISAM
wp_postmeta: Datos: 6.37MB + Índice: 1.61MB + Motor MyISAM
wp_posts: Datos: 11.06MB + Índice: 6.94MB + Motor MyISAM
wp_queue: Datos: 0.07MB + Índice: 0.00MB + Motor MyISAM
wp_redsys_reference: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_revslider_css: Datos: 0.09MB + Índice: 0.00MB + Motor MyISAM
wp_revslider_css_bkp: Datos: 0.01MB + Índice: 0.00MB + Motor MyISAM
wp_revslider_layer_animations: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_revslider_layer_animations_bkp: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_revslider_navigations: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_revslider_navigations_bkp: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_revslider_sliders: Datos: 0.02MB + Índice: 0.00MB + Motor MyISAM
wp_revslider_sliders_bkp: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_revslider_slides: Datos: 0.04MB + Índice: 0.00MB + Motor MyISAM
wp_revslider_slides_bkp: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_revslider_static_slides: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_revslider_static_slides_bkp: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_snippets: Datos: 0.01MB + Índice: 0.00MB + Motor MyISAM
wp_termmeta: Datos: 0.01MB + Índice: 0.02MB + Motor MyISAM
wp_terms: Datos: 0.01MB + Índice: 0.02MB + Motor MyISAM
wp_term_relationships: Datos: 0.04MB + Índice: 0.07MB + Motor MyISAM
wp_term_taxonomy: Datos: 0.06MB + Índice: 0.01MB + Motor MyISAM
wp_usermeta: Datos: 0.47MB + Índice: 0.23MB + Motor MyISAM
wp_users: Datos: 0.03MB + Índice: 0.04MB + Motor MyISAM
wp_wc_admin_notes: Datos: 0.01MB + Índice: 0.00MB + Motor MyISAM
wp_wc_admin_note_actions: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_wc_category_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_wc_customer_lookup: Datos: 0.03MB + Índice: 0.03MB + Motor MyISAM
wp_wc_download_log: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_wc_order_coupon_lookup: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wp_wc_order_product_lookup: Datos: 0.13MB + Índice: 0.11MB + Motor MyISAM
wp_wc_order_stats: Datos: 0.03MB + Índice: 0.03MB + Motor MyISAM
wp_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor MyISAM
wp_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.02MB + Motor MyISAM
wp_wc_reserved_stock: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_wc_tax_rate_classes: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wp_wc_webhooks: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_yikes_easy_mc_forms: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wp_yoast_indexable: Datos: 1.05MB + Índice: 0.21MB + Motor MyISAM
wp_yoast_indexable_hierarchy: Datos: 0.00MB + Índice: 0.02MB + Motor MyISAM
wp_yoast_migrations: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wp_yoast_primary_term: Datos: 0.02MB + Índice: 0.02MB + Motor MyISAM
wp_yoast_seo_links: Datos: 0.35MB + Índice: 0.07MB + Motor MyISAM
wp_yoast_seo_meta: Datos: 0.05MB + Índice: 0.04MB + Motor MyISAM

### Post Type Counts ###

attachment: 797
custom_css: 2
customize_changeset: 3
elementor_library: 13
jp_img_sitemap: 3
jp_sitemap: 3
jp_sitemap_master: 3
json_consumer: 2
mc4wp-form: 1
nav_menu_item: 62
oembed_cache: 6
page: 21
popup: 1
popup_theme: 7
post: 50
product: 197
product_variation: 6
revision: 1789
shop_coupon: 17
shop_order: 399
shop_order_refund: 3
sp_wps_shortcodes: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (36) ###

Adapta RGPD: por Superadmin – 1.3.1
Akismet Anti-Spam: por Automattic – 4.1.7
Autoptimize: por Frank Goossens (futtta) – 2.7.8
Classic Editor: por WordPress Contributors – 1.6
Code Snippets: por Code Snippets Pro – 2.14.0
Join.chat: por Creame – 4.1.0
Customer Reviews for WooCommerce: por Reseñas de clientes – 3.132
Disable Cart Fragments: por Optimocha – 1.21 – Versión instalada no está probada con la versión activa de WooCommerce 4.6.1
Doofinder for WooCommerce: por doofinder – 1.2.22 – Versión instalada no está probada con la versión activa de WooCommerce 4.6.1
Yoast Duplicate Post: por Enrico Battocchi & Team Yoast – 3.2.6
Elementor: por Elementor.com – 3.0.13
Enhanced E-commerce for Woocommerce store: por Tatvic – 2.3.6.1
EWWW Image Optimizer: por Exactly WWW – 5.8.1
Facebook for WooCommerce: por Facebook – 2.1.4
Jetpack by WordPress.com: por Automattic – 9.0.2
WPBakery Page Builder: por Michael M - WPBakery.com – 6.0.5
Mailchimp for WooCommerce: por Mailchimp – 2.4.7 – Versión instalada no está probada con la versión activa de WooCommerce 4.6.1
MC4WP: Mailchimp for WordPress: por ibericode – 4.8.1
Max Mega Menu: por megamenu.com – 2.9.1
Packlink PRO Shipping: por Packlink Shipping S.L. – 3.0.5 – Versión instalada no está probada con la versión activa de WooCommerce 4.6.1
Perfect Brands for WooCommerce: por QuadLayers – 1.8.5
Table of Contents Plus: por Michael Tran – 2002
ThemeREX Utilities: por ThemeREX – 3.2.4
UpdraftPlus - Backup/Restore: por UpdraftPlus.Com
DavidAnderson – 1.16.34

WooCommerce Product Feed: por WebAppick – 4.1.3 – Versión instalada no está probada con la versión activa de WooCommerce 4.6.1
Woo Button Text: por Rupom Khondaker – 6.0.3 – Versión instalada no está probada con la versión activa de WooCommerce 4.6.1
Product Slider for WooCommerce: por ShapedPlugin – 2.2.4
Woocommerce Table Rate Shipping: por JEM Plugins – 2.0.9 – Versión instalada no está probada con la versión activa de WooCommerce 4.6.1
EU VAT Compliance for WooCommerce (Free): por David Anderson – 1.14.25
WooCommerce Stripe Gateway: por WooCommerce – 4.5.3 – Versión instalada no está probada con la versión activa de WooCommerce 4.6.1
WooCommerce Menu Cart: por Jeremiah Prummer
Ewout Fernhout – 2.9.6

WooCommerce Shipping & Tax: por Automattic – 1.25.1 – Versión instalada no está probada con la versión activa de WooCommerce 4.6.1
WooCommerce: por Automattic – 4.6.1
Yoast SEO: por Equipo Yoast – 15.2.1
WP Super Cache: por Automattic – 1.7.1
Easy Forms for MailChimp: por YIKES
Inc. – 6.8.0

### Inactive Plugins (4) ###

Essential Grid: por ThemePunch – 2.3.3
Popup Maker: por Popup Maker – 1.13.0
Quick View WooCommerce: por XootiX – 1.7 – Versión instalada no está probada con la versión activa de WooCommerce 4.6.1
Slider Revolution: por ThemePunch – 6.1.2

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (3) ###

Elementor Safe Mode: por Elementor.com – 1.0.0
p3-profiler.php: por  –
WP REST API - OAuth 1.0a Server: por WP REST API Team – 0.3.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Base de la tienda: #1071 - /
Carrito: #1072 - /carrito/
Finalizar compra: #1073 - /finalizar-compra/
Mi cuenta: #1074 - /mi-cuenta/
Términos y condiciones: #1350 - /terminos-y-condiciones/

### Theme ###

Name: Organics
Version: 1.5.7
Author URL: http://axiomthemes.net/
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Cancelada: 4
Oldest: 2020-10-07 19:36:42 +0200
Newest: 2020-11-04 22:02:08 +0100

Completo: 5.343
Oldest: 2020-10-05 04:24:52 +0200
Newest: 2020-11-05 03:17:44 +0100

Fallida: 66
Oldest: 2020-03-28 20:46:01 +0100
Newest: 2020-03-28 20:46:01 +0100

Pendiente: 1
Oldest: 2020-11-05 03:32:44 +0100
Newest: 2020-11-05 03:32:44 +0100

`

**Comment by simonporter007** [comment] 2020-11-09 17:32
Hey @kunaqeduardo,

Thanks for writing in! Our developers have made some changes to the product category functionality in the most recent version that should avoid the issues we were seeing. Would it be possible to update to the latest version and let me know if you're still seeing this problem?

Cheers!

**Comment by pettreegnat** [comment] 2020-11-20 05:02
Still seeing the problem here

**Comment by pettreegnat** [comment] 2020-11-22 01:23
From what i understand this is fairly widespread, as it affects anyone using yoast.

**Comment by danielbitzer** [comment] 2021-05-06 03:20
This issue was caused by PHP memory exhaustion when parsing a large .json file. It was fixed by #1853 and released in 2.4.0.

Let us know if the issue persists after updating to 2.4.0.

**Closed** 2021-05-06 03:23 UTC
Labels: feature: product sync, google product categories
