### ISSUE TITLE
Server Sending Invalid Match Key Parameters for AddToCart Event

### ISSUE THREAD

**Issue by ishanirajyaguru** [woocommerce/facebook-for-woocommerce#2137] opened 2022-01-03 05:47 UTC
We are getting error on our website inkydeals.com

Can you please let me know the solution.

1 | Issue: Server Sending Invalid Match Key Parameters for AddToCart EventYour server is sending an invalid parameters value for your AddToCart event. This may be because there was an error in the parameter value.
-- | --

**Comment by jconroy** [comment] 2022-02-28 03:03
Closing as a duplicate of https://github.com/woocommerce/facebook-for-woocommerce/issues/1777

**Closed by jconroy** 2022-02-28 03:03 UTC
