### ISSUE TITLE
Chat widget doesnt appear when using ad blocker

### ISSUE THREAD

**Issue by danielboos1** [woocommerce/facebook-for-woocommerce#2255] opened 2022-07-23 19:45 UTC
## 🔎 Isolate the bug

- [X ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

When you enable the chat widget, and the user has an ad blocker the ad blocker blocks the widget and never appears.
## 🚶‍♀️ Steps to reproduce

Enable chat widget from the plugin
Use ad blocker when visiting the website.
## ✔️ Expected behavior

The chat widget shouldn't be blocked from the ad blocker.

**Comment by rawdreeg** [comment] 2022-09-13 12:19
Thanks for the report. I could not reproduce this using AdBlock Plus on Google Chrome. Also, if an AdBlocker stops the FB script from loading, this is not an issue we'd be able to fix on the plugin, unfortunately. Therefore, I will be closing this issue.

**Closed by rawdreeg** 2022-09-13 12:19 UTC
Labels: needs investigation, priority: low
