### ISSUE TITLE
Agencies cannot use the plugin anymore

### ISSUE THREAD

**Issue by coccoinomane** [woocommerce/facebook-for-woocommerce#1718] opened 2020-11-30 17:30 UTC
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

Hello,
At my web agency we have been using Facebook for WooCommerce with success until today.
After updating from v1.9.15 to v2.1.4, we are asked to reconnect to Facebook (screenshot => https://idearia.link/NJknra) but when we do it, we are not allowed to select neither the Product Catalog nor the Facebook page because they belong to another Business Manager (screenshot => https://idearia.link/FSdrtK).
This should not happen, because we are administrators of both the Product catalog and the Page, via our agency’s Business manager, which is authorized by the client’s Business manager.
Is there a workaround? We are considering downgrading to v1.9.15, but it would not be ideal.
Thank you for your attention,
Guido

## 🚶‍♀️ Steps to reproduce

1 You are admin of page and catalog, but your business manager is not the owner of these resources.
2. Try to setup the plugin.
3. You will get this error => https://idearia.link/FSdrtK

**Comment by coccoinomane** [comment] 2020-11-30 18:29
Please note that downgrading to Facebook for WooCommerce v1.10.2 seems to work as a temporary fix.

**Comment by coccoinomane** [comment] 2021-01-15 14:15
Hello,
I have read [on the WordPress forum](https://wordpress.org/support/topic/cant-connect-anymore-to-facebook-after-update-to-v2-1-4/) the good news that the issue will be addressed by the dev team, thanks!
Is there any ETA attached to this issue?
Cheers,
Guido

**Comment by battouly** [comment] 2021-01-15 14:31
We have seen the same report from other users, and I was able to replicate the behavior. 
As for the ETA there's no ETA yet. The devs will take a look at it soon and update here.

**Comment by haszari** [comment] 2021-04-16 01:07
Closing this as a duplicate of #1453.

**Closed by haszari** 2021-04-16 01:07 UTC
Labels: feature: onboarding, priority: high, type: bug
