### ISSUE TITLE
website died when I updated the plugin.

### ISSUE THREAD

**Issue by hyhuman** [woocommerce/facebook-for-woocommerce#2160] opened 2022-02-22 16:35 UTC
received this message: 

Parse error: syntax error, unexpected ')' in /home/tinypinc/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php on line 709

Notice: is_page was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 3.1.0.) in /home/tinypinc/public_html/wp-includes/functions.php on line 5768

Notice: is_singular was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 3.1.0.) in /home/tinypinc/public_html/wp-includes/functions.php on line 5768

Notice: is_embed was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 3.1.0.) in /home/tinypinc/public_html/wp-includes/functions.php on line 5768

Notice: is_search was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 3.1.0.) in /home/tinypinc/public_html/wp-includes/functions.php on line 5768
There has been a critical error on this website. Please check your site admin email inbox for instructions.

**Comment by rashedripon** [comment] 2022-02-22 20:39
I couldn't reproduce this while using the latest WooCommerce + WordPress but a few other people faced the same here: https://wordpress.org/support/topic/fatal-error-on-version-2-6-10/

They also identified the problem & a solution: https://wordpress.org/support/topic/fatal-error-on-version-2-6-10/#post-15390977

**Comment by wojsmol** [comment] 2022-02-22 23:29
@rashedripon and reported as https://github.com/woocommerce/facebook-for-woocommerce/issues/2157 😄 Please post your environment info the mentioned issue

**Comment by matthewmeaklim** [comment] 2022-02-23 07:41
Also getting this exact same error.

**Comment by wojsmol** [comment] 2022-02-23 08:53
@matthewmeaklim Please post this information in  #2157. Include exact versions and add PHP version used.

**Comment by smkamranqadri** [comment] 2022-02-25 19:26
Same happened to my site.
<img width="859" alt="Screenshot 2022-02-26 at 12 24 11 AM" src="https://user-images.githubusercontent.com/13115396/155775934-b1d1f911-8d26-4096-bc46-ffbcbe4a0049.png">

**Comment by jconroy** [comment] 2022-02-28 02:13
Closing as a duplicate of https://github.com/woocommerce/facebook-for-woocommerce/issues/2157

**Closed by jconroy** 2022-02-28 02:13 UTC
