### ISSUE TITLE
[WPML and Facebook for WooCommerce] incorrect currency on translated products synced to Facebook

### ISSUE THREAD

**Issue by andrescifuentesr** [woocommerce/facebook-for-woocommerce#2525] opened 2023-04-25 06:22 UTC
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

When using WPML with Facebook for WooCommerce the translated products synced to Facebook display an incorrect currency. This is due to Facebook for WooCommerce taking the currency from WooCommerce settings and not from WPML’s multi-currency settings.
In the meantime, we have published this erratum. But it will be great if we can integrate this feature. 
https://wpml.org/errata/facebook-for-woocommerce-multi-currency-is-not-supported/

## 🚶‍♀️ Steps to reproduce

1. Activate WPML and WooCommerce Multilingual.
2. Set the multi-currency feature with 2 currencies (based on language).
3. Create 1 product, translate it. Set custom price for the secondary language.
4. Install Facebook for WooCommerce and configure an online store.
5. Sync the product to Facebook (Marketing > Facebook > Product Sync > "Sync products" button).
6. In the catalogue, both product variants show with the same price and currency of the default language
![fb-for-woocommerce](https://user-images.githubusercontent.com/3823815/234190482-d01d4e93-3630-44a7-b2be-971c84521396.jpg)

## ✔️ Expected behavior

The translated product should show up with the correct price and currency.

**Comment by layoutd** [comment] 2023-04-25 12:29
Thanks for reporting @andrescifuentesr, we'll discuss this and determine the best course of action.

**Comment by andrescifuentesr** [comment] 2023-04-26 05:57
Thank you @layoutd. Don't hesitate to let me know if there is anything we can do in order to help moving this forward.

**Comment by layoutd** [comment] 2023-04-28 12:48
Hi again @andrescifuentesr, it appears this behavior is actually by design: [since ~2018](https://github.com/woocommerce/facebook-for-woocommerce/commit/0613fa19fbab47f7bdff9c136e7c5230d66d69ef#diff-2c6105d743276adbdf48a5176de319e632eadf09dbe99ed88e9e3ca939e57b04R433-R446) the Facebook for WooCommerce plugin sets all products to `hidden` if they aren't in a store's main language (and therefore currency):
https://github.com/woocommerce/facebook-for-woocommerce/blob/070bb144b4f47f634219dcb97d99a0fb9213dff8/includes/fbproduct.php#L608-L614

These products _will_ be uploaded to the catalog on Facebook, but will be marked as [Archived](https://www.facebook.com/business/help/543317109402043?id=725943027795860) and thus invisible (confirmed in the screenshot above, as to see the erroneous products in the Facebook catalog, you have to toggle from `Active` to `All`). 

In order to list products in multiple currencies on Facebook, [it's necessary to create multiple feeds by country/language](https://www.facebook.com/business/help/127019799344394), which this plugin doesn't currently support.

**Closed** 2023-04-28 12:50 UTC
Labels: needs investigation

**Comment by sukafia** [comment] 2023-05-09 07:21
6270722-zen
