### ISSUE TITLE
I made an update yesterday and it blocked my access to my Dashbord Wordpress. The extension has a problem. I had to deactivate it to access my Dashboard. Please fix this issue soon

### ISSUE THREAD

**Issue by rafik-10** [woocommerce/facebook-for-woocommerce#2161] opened 2022-02-23 10:52 UTC

**Comment by wojsmol** [comment] 2022-02-23 14:11
@rafik-10 Please see https://github.com/woocommerce/facebook-for-woocommerce/issues/2157 there is a temporary fix for this in the first post. If the fix works for you then post your environment details in mentioned issue.

**Comment by jconroy** [comment] 2022-02-28 02:15
Assuming this is a duplicate of https://github.com/woocommerce/facebook-for-woocommerce/issues/2157 - closing for now unless there is more information/a different error to add

**Closed by jconroy** 2022-02-28 02:15 UTC
