### ISSUE TITLE
Catalog ID is missing

### ISSUE THREAD

**Issue by sukafia** [woocommerce/facebook-for-woocommerce#2241] opened 2022-07-02 10:41 UTC
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

A number of users are reporting getting the error `Catalog ID is missing` when setting up the Facebook for WooCommerce extension. This error appears to be returned when the "Return to WooCommerce integration" button is clicked.

I noticed Facebook/Instagram shop isn't supported in the countries of most of the affected users. Also, this issue happens when they try to reconnect the extension after disconnecting to fix a sync issue, etc. (it doesn't happen during the initial setup)

## 🚶‍♀️ Steps to reproduce

While I'm not sure of the exact steps, it appears to be:

1. Setup Facebook for WooCommerce extension in a location Facebook/Instagram shop isn't supported
2. Allow products to sync to Facebook
3. Disconnect the extension and try to set it up again

## Support requests

- https://wordpress.org/support/topic/catalog-id-is-missing/
- https://wordpress.org/support/topic/error-catalog-id-is-missing-redirecting-from-facebook-setup/
- https://wordpress.org/support/topic/catalog-id-is-missing-error/
- https://wordpress.org/support/topic/catalog-id-is-missing-2/

A user was able to resolve the issue by [setting up the connection directly from Facebook](https://wordpress.org/support/topic/catalog-id-is-missing-error/page/2/#post-15722080) using Facebook business apps.

**Comment by rawdreeg** [comment] 2022-07-05 09:42
Thanks, @sukafia for this issue. We're currently investigating this. I just have a question:

> Setup Facebook for WooCommerce extension in a location Facebook/Instagram shop isn't supported

Is this to woocommerce location or is there a way to change location in FB?

**Comment by sukafia** [comment] 2022-07-05 13:35
> Thanks, @sukafia for this issue. We're currently investigating this. I just have a question:
> 
> > Setup Facebook for WooCommerce extension in a location Facebook/Instagram shop isn't supported
> 
> Is this the WooCommerce location or is there a way to change location in FB?

Looks like it'd have to be both. The location in FB is based on the account country. So you may have to create a new FB account to test with.

**Comment by rawdreeg** [comment] 2022-07-08 14:52
Thanks @sukafia 

I was not able to reproduce this issue even after I successfully simulated an account using a location not supported by FB:

![Screenshot 2022-07-05 at 16 25 33](https://user-images.githubusercontent.com/4209011/178015213-6016845a-2ec3-4961-bd1f-a2f5a309b89d.jpg)

I was able to trigger `Could not retrieve Facebook Business Extension System User` relatively consistently by triggering a connection error :

1. Go to wp-admin > Marketing > Facebook and click Manage connection. You should land on a Facebook Business Extension settings page.
2. Click the three-dots button next to WooCommerce Integration and click Uninstall in the dropdown and follow the prompts to disconnect.
3. Go back to the store backend, and try performing a product sync. This will display an error notice, and upon attempting to reconnect, I get the `Could not retrieve Facebook Business Extension System User`. 

Not sure if this is at all related. but I will keep looking into this. And you can share a recording of the error, that will be helpful.

Thanks

**Comment by ericfri** [comment] 2022-07-21 19:53
I too received the `Could not retrieve Facebook Business Extension System User` error.
The only way I was able to fix it was by deleting my catalog in Facebook and starting over. Once the catalog was removed, things went as expected.

**Comment by rawdreeg** [comment] 2022-07-22 15:56
Thanks @ericfri.

@sukafia could you check if @ericfri 's [solution](https://github.com/woocommerce/facebook-for-woocommerce/issues/2241#issuecomment-1191874486) works for you?

Thanks,
R

**Comment by budzanowski** [comment] 2022-09-07 12:04
I am closing this as it looks like `Could not retrieve Facebook Business Extension System User` is a solution, at least for the reconnection scenario. And since @rawdreeg had no luck in recreating the unsupported country scenario we don't have a way to proceed.

@sukafia Please reopen in case we will encounter other instances.

**Closed by budzanowski** 2022-09-07 12:04 UTC
Labels: needs investigation, priority: high, type: bug, needs feedback
