### ISSUE TITLE
is_ajax depecrated issue

### ISSUE THREAD

**Issue by sundios** [woocommerce/facebook-for-woocommerce#2142] opened 2022-01-13 02:42 UTC
Having issues with this plugin because of the removal of is_ajax. Im getting the following error:

**Deprecated: is_ajax is deprecated since version 6.1.0! Use wp_doing_ajax instead. in /home/sundios/californiadumbbells.com/wp-includes/functions.php on line 5211**

I turn off all my woocommerce add on plugins and this was the one causing this issue. 

Solution is pretty simple, we need to switch **is_ajax** for **wp_doing_ajax**

**Comment by Elis1991-ctrl** [comment] 2022-01-13 15:21
Hi, same problem solved by deactivating the Facebook for Woocommerce plugin. Since it's a plugin I need, is there any way to fix it and then reactivate it?

**Comment by kieron** [comment] 2022-01-13 16:32
This has already been reported here https://github.com/woocommerce/facebook-for-woocommerce/issues/2133

**Comment by joashrajin** [comment] 2022-01-14 11:00
Closing since it is a duplicate of https://github.com/woocommerce/facebook-for-woocommerce/issues/2133

**Closed by joashrajin** 2022-01-14 11:00 UTC
