### ISSUE TITLE
Variable products' category does not sync to Facebook

### ISSUE THREAD

**Issue by tijosh** [woocommerce/facebook-for-woocommerce#1775] opened 2021-02-16 19:21 UTC
## ✍️ Describe the bug
Category is lost for variable products when synced to Facebook:

![Screenshot](https://d.pr/i/gUjTBl+)
*Link to image: https://d.pr/i/gUjTBl*

##🚶‍♀️ Steps to reproduce

1. Create variable product with category
2. See missing category on Facebook catalogue
3. 
## ✔️ Expected behavior

The category is displayed.

**Comment by cmaile** [comment] 2021-02-24 10:50
I can confirm:

Wordpress: Version 5.6.2
WooCommerce:  Version 5.0.0
Facebook for WooCommerce: Version 2.3.1

**Comment by cmaile** [comment] 2021-02-28 17:22
The following changes fixes the problem, but im not sure if that the correct fix:

`diff --git a/includes/ProductSets/Sync.php b/includes/ProductSets/Sync.php
index 0b61317d..1b39f607 100644
--- a/includes/ProductSets/Sync.php
+++ b/includes/ProductSets/Sync.php
@@ -367,7 +367,7 @@ class Sync {

                                array_push(
                                        $products,
-                                       array( 'retailer_id' => array( 'eq' => $fb_retailer_id ) )
+                                       array( 'retailer_product_group_id' => array( 'eq' => $fb_retailer_id ) )
                                );
                        }
                }
@@ -380,7 +380,7 @@ class Sync {

                        array_push(
                                $products,
-                               array( 'retailer_id' => array( 'eq' => $fb_retailer_id ) )
+                               array( 'retailer_product_group_id' => array( 'eq' => $fb_retailer_id ) )
                        );
                }`

**Comment by rcstr** [comment] 2021-03-11 02:07
I been looking in this and [`[/{catalog_id}/items_batch`](https://developers.facebook.com/docs/marketing-api/catalog-batch/reference#supported-fields-items-batch) doesn't accepts `category` field which [`POST [/{catalog_id}/batch`](https://developers.facebook.com/docs/marketing-api/catalog-batch/reference#supported-fields-batch) does. The request response when `category` field is included returns: `{"message":"Unrecognized field: A request for item Woo-beanie-logo_32 contains unrecognized field category"}`.

**Comment by rcstr** [comment] 2021-03-16 01:23
Hey @denniskwon, do you know how we can proceed here since the API doesn't have the `category` field anymore(see my previous comment)?.

cc: @haszari @jconroy

**Comment by neiltownsend** [comment] 2021-03-30 15:27
I can also confirm that variation products don't update the Woocommerce set category name as the category. A numeric value is set corresponding to the Google category selected.

I trialled the two code amendments above, without changing the result.

**Comment by rawdreeg** [comment] 2022-05-11 12:05
I was not able to reproduce this. I am able to sync the categories on variable products with no problem.

![Screenshot 2022-05-11 at 13 55 50](https://user-images.githubusercontent.com/4209011/167845417-8c8cf526-d286-421c-9b02-73f0bd9f9762.jpg)

I will close this. Feel free to open another issue if you still have problems with this.

R

**Closed by rawdreeg** 2022-05-11 12:05 UTC
Labels: type: bug, feature: product sync
