### ISSUE TITLE
I just upgraded the plugin and my site was crashed. Now the hosting service has put the site back by de-activate the plugin. What should i do to re-active the plugin without having my site crashing again?

### ISSUE THREAD

**Issue by cinaintavola** [woocommerce/facebook-for-woocommerce#2158] opened 2022-02-22 14:08 UTC
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## 🚶‍♀️ Steps to reproduce

1. The first step
1. The next step… 

## 🗃 Logs

<details>
	
</details>

**Comment by zafarSubhani** [comment] 2022-02-22 14:56
please remove "," at line 709 in functions.php file in folder wp-include

**Comment by wojsmol** [comment] 2022-02-22 15:10
This is a duplicate of https://github.com/woocommerce/facebook-for-woocommerce/issues/2157

**Closed** 2022-02-22 20:38 UTC
