### ISSUE TITLE
Facebook connection error

### ISSUE THREAD

**Issue by hovardazeus** [woocommerce/facebook-for-woocommerce#2151] opened 2022-02-11 14:23 UTC
```
WooCommerce for Facebook error:
Unsupported post request. Object with ID '4596744727076604' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api
```

I am getting such a warning. How can I solve this problem?

**Comment by jconroy** [comment] 2022-02-28 02:35
Closing as a duplicate of https://github.com/woocommerce/facebook-for-woocommerce/issues/1689

**Closed by jconroy** 2022-02-28 02:35 UTC
